"""Zentrale Standardwerte — unabhängig von Pfad- und DB-Konfiguration."""

from __future__ import annotations

DEFAULT_WORK_SUBDIR = "_otio"
DEFAULT_VOICE_OVER_SUBDIR = "Voice over"
DEFAULT_FRAMES_PER_SHOT = 3
DEFAULT_GEMINI_MODEL = "gemini-3.1-flash-lite"
DEFAULT_VOICE_BACKEND = "whisper"
DEFAULT_WHISPER_MODEL = "large-v3"
VOICE_BACKEND_WHISPER = "whisper"
VOICE_BACKEND_GEMINI = "gemini"
VOICE_BACKEND_CHOICES = (
    VOICE_BACKEND_WHISPER,
    VOICE_BACKEND_GEMINI,
)
VOICE_BACKEND_LABELS = {
    VOICE_BACKEND_WHISPER: "Whisper (lokal, kostenlos)",
    VOICE_BACKEND_GEMINI: "Gemini (Cloud, kostenpflichtig)",
}
WHISPER_MODEL_CHOICES = (
    "tiny",
    "base",
    "small",
    "medium",
    "large-v3",
)
WHISPER_MODEL_LABELS = {
    "tiny": "Whisper tiny — am schnellsten, grober",
    "base": "Whisper base — schnell",
    "small": "Whisper small — schnell, ausgewogen",
    "medium": "Whisper medium — genauer, langsamer",
    "large-v3": "Whisper large-v3 — beste Qualität, am langsamsten (Standard)",
}
GEMINI_MODEL_CHOICES = (
    "gemini-3-flash-preview",
    "gemini-3.1-flash-lite",
    "gemini-3.1-pro-preview",
)
GEMINI_MODEL_LABELS = {
    "gemini-3-flash-preview": "Gemini 3 Flash Preview — schnell, Pro-Niveau (Preview)",
    "gemini-3.1-flash-lite": "Gemini 3.1 Flash Lite — günstig, Preview (Standard)",
    "gemini-3.1-pro-preview": "Gemini 3.1 Pro Preview — beste Qualität (Preview, teurer)",
}

OPENAI_PLAN_MODEL_CHOICES = (
    "openai:gpt-5.5",
    "openai:gpt-5.4-mini",
)
ANTHROPIC_PLAN_MODEL_CHOICES = (
    "anthropic:claude-opus-4-8",
    "anthropic:claude-sonnet-5",
)
EDIT_PLAN_MODEL_CHOICES = GEMINI_MODEL_CHOICES + OPENAI_PLAN_MODEL_CHOICES + ANTHROPIC_PLAN_MODEL_CHOICES
EDIT_PLAN_MODEL_LABELS = {
    **GEMINI_MODEL_LABELS,
    "openai:gpt-5.5": "ChatGPT GPT-5.5 — Flagship, beste Qualität",
    "openai:gpt-5.4-mini": "ChatGPT GPT-5.4 mini — günstig, schnell",
    "anthropic:claude-opus-4-8": "Claude Opus 4.8 — Flagship, beste Qualität",
    "anthropic:claude-sonnet-5": "Claude Sonnet 5 — ausgewogen, günstiger",
}
INVENTORY_FILENAME = "inventory.json"
INVENTORY_SUBDIR = "inventory"
MANUAL_FOLDER_COMPLETION_FILENAME = "manual_folder_completion.json"
VOICE_ANALYSIS_FILENAME = "voice_over_analysis.json"
VOICE_FOLDER_MAPPING_FILENAME = "voice_folder_mapping.json"
EDIT_PLAN_FILENAME = "edit_plan.json"
EDIT_PLAN_SUBDIR = "edit_plan"

PROJECT_MODE_WITH_VOICEOVER = "with_voiceover"
PROJECT_MODE_WITHOUT_VOICEOVER = "without_voiceover"
PROJECT_MODE_CHOICES = (PROJECT_MODE_WITH_VOICEOVER, PROJECT_MODE_WITHOUT_VOICEOVER)
PROJECT_MODE_LABELS = {
    PROJECT_MODE_WITH_VOICEOVER: "Projekt mit Voice-Over",
    PROJECT_MODE_WITHOUT_VOICEOVER: "Projekt ohne Voice-Over",
}

VOICEOVER_GENERATION_SUBDIR = "voiceover_generation"
VOICEOVER_GENERATION_LLM_RUNS_SUBDIR = "llm_runs"
VOICEOVER_GENERATION_AUDIO_SUBDIR = "audio"
VOICEOVER_GENERATION_TTS_RUNS_SUBDIR = "tts_runs"
VOICEOVER_GENERATION_INTRO_AUDIO_FOLDER_NAME = "000_intro"
STYLE_REFERENCES_SUBDIR = "style_references"
STYLE_REFERENCES_UPLOADS_SUBDIR = "uploads"
MODEL_SETTINGS_FILENAME = "model_settings.json"

PROJECT_BRIEF_FILENAME = "project_brief.json"
VOICEOVER_STYLE_REFERENCES_FILENAME = "voiceover_style_references.json"
VOICEOVER_STYLE_PROFILE_FILENAME = "voiceover_style_profile.json"
DRAMATURGY_PLAN_DRAFT_FILENAME = "dramaturgy_plan.draft.json"
DRAMATURGY_PLAN_CONFIRMED_FILENAME = "dramaturgy_plan.confirmed.json"
FOLDER_VOICEOVER_SETTINGS_FILENAME = "folder_voiceover_settings.json"
FOLDER_VOICEOVERS_DRAFT_FILENAME = "folder_voiceovers.draft.json"
FOLDER_VOICEOVER_VALIDATION_REPORT_FILENAME = "folder_voiceover_validation_report.json"
FOLDER_VOICEOVERS_CONFIRMED_FILENAME = "folder_voiceovers.confirmed.json"
INTRO_HOOK_CANDIDATES_FILENAME = "intro_hook_candidates.json"
INTRO_HOOK_CONFIRMED_FILENAME = "intro_hook.confirmed.json"
ELEVENLABS_SETTINGS_FILENAME = "elevenlabs_settings.json"
VOICEOVER_AUDIO_MANIFEST_FILENAME = "voiceover_audio_manifest.json"
VOICEOVER_AUDIO_QA_REPORT_FILENAME = "voiceover_audio_qa_report.json"
CONFIRMED_VOICEOVER_PROJECT_PLAN_FILENAME = "confirmed_voiceover_project_plan.json"
VOICEOVER_PROJECT_PLAN_JSON_FILENAME = "voiceover_project_plan.json"
VOICEOVER_PROJECT_PLAN_MD_FILENAME = "voiceover_project_plan.md"
VOICEOVER_PROJECT_PLAN_CSV_FILENAME = "voiceover_project_plan.csv"

# --- LLM-Provider/Modell-Presets für die Voice-over-Generierungs-Pipeline ---
# Eigenständig von EDIT_PLAN_MODEL_CHOICES: hier werden provider und model als
# getrennte Felder gespeichert (siehe VoiceoverGenerationModelSettings), daher
# ohne "anthropic:"/"openai:"-Präfix.
VOICEOVER_GEN_PROVIDERS = ("anthropic", "openai", "gemini")
VOICEOVER_GEN_MODEL_PRESETS: dict[str, tuple[str, ...]] = {
    "anthropic": ("claude-opus-4-8", "claude-sonnet-5", "claude-haiku-4-5"),
    "openai": ("gpt-5.5", "gpt-5.4-mini"),
    "gemini": ("gemini-3.1-pro-preview", "gemini-3.1-flash-lite"),
}
VOICEOVER_GEN_ROLE_STYLE_PROFILE = "style_profile"
VOICEOVER_GEN_ROLE_DRAMATURGY = "dramaturgy"
VOICEOVER_GEN_ROLE_VOICEOVER_AUTHOR = "voiceover_author"
VOICEOVER_GEN_ROLE_VOICEOVER_REVIEW = "voiceover_review"
VOICEOVER_GEN_ROLE_INTRO = "intro"
VOICEOVER_GEN_ROLES = (
    VOICEOVER_GEN_ROLE_STYLE_PROFILE,
    VOICEOVER_GEN_ROLE_DRAMATURGY,
    VOICEOVER_GEN_ROLE_VOICEOVER_AUTHOR,
    VOICEOVER_GEN_ROLE_VOICEOVER_REVIEW,
    VOICEOVER_GEN_ROLE_INTRO,
)
VOICEOVER_GEN_ROLE_LABELS = {
    VOICEOVER_GEN_ROLE_STYLE_PROFILE: "Style Profile",
    VOICEOVER_GEN_ROLE_DRAMATURGY: "Dramaturgie",
    VOICEOVER_GEN_ROLE_VOICEOVER_AUTHOR: "Voice-over Autor",
    VOICEOVER_GEN_ROLE_VOICEOVER_REVIEW: "Voice-over Review",
    VOICEOVER_GEN_ROLE_INTRO: "Intro",
}
VOICEOVER_GEN_DEFAULT_PROVIDER = "anthropic"
VOICEOVER_GEN_DEFAULT_MODEL = "claude-sonnet-5"

# --- Project Brief: feste Auswahllisten ---
BRIEF_LANGUAGE_CHOICES = ("DE", "EN", "FR", "ES", "PT", "IT")
BRIEF_TONE_TAG_CHOICES = (
    "cinematic",
    "documentary",
    "discovery",
    "calm",
    "dramatic",
    "premium travel",
    "mysterious",
    "energetic",
    "poetic but factual",
    "high-end YouTube documentary",
)
BRIEF_NEGATIVE_RULE_NO_INVENTED_FACTS = "no_invented_facts"
BRIEF_NEGATIVE_RULE_NO_EXAGGERATED_SUPERLATIVES = "no_exaggerated_superlatives"
BRIEF_NEGATIVE_RULE_NO_CLICKBAIT_PHRASES = "no_clickbait_phrases"
BRIEF_NEGATIVE_RULE_NO_REPETITION = "no_repetition"
BRIEF_NEGATIVE_RULE_NO_DIRECT_VIEWER_ADDRESS = "no_direct_viewer_address"
BRIEF_NEGATIVE_RULE_NO_IN_THIS_VIDEO_PHRASING = "no_in_this_video_phrasing"
BRIEF_NEGATIVE_RULE_NO_UNVERIFIED_HISTORICAL_CLAIMS = "no_unverified_historical_claims"
BRIEF_NEGATIVE_RULE_NOT_JUST_ASSET_DESCRIPTIONS = "not_just_asset_descriptions"
BRIEF_NEGATIVE_RULE_DOCUMENTARY_PROSE_REQUIRED = "documentary_prose_required"
BRIEF_NEGATIVE_RULE_FLAGS = (
    BRIEF_NEGATIVE_RULE_NO_INVENTED_FACTS,
    BRIEF_NEGATIVE_RULE_NO_EXAGGERATED_SUPERLATIVES,
    BRIEF_NEGATIVE_RULE_NO_CLICKBAIT_PHRASES,
    BRIEF_NEGATIVE_RULE_NO_REPETITION,
    BRIEF_NEGATIVE_RULE_NO_DIRECT_VIEWER_ADDRESS,
    BRIEF_NEGATIVE_RULE_NO_IN_THIS_VIDEO_PHRASING,
    BRIEF_NEGATIVE_RULE_NO_UNVERIFIED_HISTORICAL_CLAIMS,
    BRIEF_NEGATIVE_RULE_NOT_JUST_ASSET_DESCRIPTIONS,
    BRIEF_NEGATIVE_RULE_DOCUMENTARY_PROSE_REQUIRED,
)
BRIEF_NEGATIVE_RULE_LABELS = {
    BRIEF_NEGATIVE_RULE_NO_INVENTED_FACTS: "Keine erfundenen Fakten",
    BRIEF_NEGATIVE_RULE_NO_EXAGGERATED_SUPERLATIVES: "Keine übertriebenen Superlative",
    BRIEF_NEGATIVE_RULE_NO_CLICKBAIT_PHRASES: "Keine Clickbait-Floskeln",
    BRIEF_NEGATIVE_RULE_NO_REPETITION: "Keine Wiederholungen",
    BRIEF_NEGATIVE_RULE_NO_DIRECT_VIEWER_ADDRESS: "Keine direkte Zuschaueransprache",
    BRIEF_NEGATIVE_RULE_NO_IN_THIS_VIDEO_PHRASING: 'Keine Formulierungen wie "in diesem Video"',
    BRIEF_NEGATIVE_RULE_NO_UNVERIFIED_HISTORICAL_CLAIMS: "Keine unbelegten historischen Behauptungen",
    BRIEF_NEGATIVE_RULE_NOT_JUST_ASSET_DESCRIPTIONS: "Nicht nur Assetbeschreibungen",
    BRIEF_NEGATIVE_RULE_DOCUMENTARY_PROSE_REQUIRED: "Text muss wie echte Doku-Prosa klingen",
}
DEFAULT_NEGATIVE_RULE_FLAGS: dict[str, bool] = {flag: True for flag in BRIEF_NEGATIVE_RULE_FLAGS}

# --- Dramaturgie: Wortanzahl-Heuristik pro Ordner (Phase 3) ---
# Ausgangsheuristik — soll später in der UI pro Projekt überschreibbar sein.
VOICEOVER_GEN_DEFAULT_WORD_TOLERANCE_PERCENT = 10
VOICEOVER_GEN_MIN_FOLDER_WORDS = 50
VOICEOVER_GEN_MAX_FOLDER_WORDS = 180

FOLDER_INVENTORY_SUMMARIES_FILENAME = "folder_inventory_summaries.json"

DRAMATURGY_ROLE_OPENER = "opener"
DRAMATURGY_ROLE_SETUP = "setup"
DRAMATURGY_ROLE_CONTRAST = "contrast"
DRAMATURGY_ROLE_ESCALATION = "escalation"
DRAMATURGY_ROLE_CLIMAX = "climax"
DRAMATURGY_ROLE_RESOLUTION = "resolution"
DRAMATURGY_ROLES = (
    DRAMATURGY_ROLE_OPENER,
    DRAMATURGY_ROLE_SETUP,
    DRAMATURGY_ROLE_CONTRAST,
    DRAMATURGY_ROLE_ESCALATION,
    DRAMATURGY_ROLE_CLIMAX,
    DRAMATURGY_ROLE_RESOLUTION,
)
DRAMATURGY_ROLE_LABELS = {
    DRAMATURGY_ROLE_OPENER: "Opener",
    DRAMATURGY_ROLE_SETUP: "Setup",
    DRAMATURGY_ROLE_CONTRAST: "Kontrast",
    DRAMATURGY_ROLE_ESCALATION: "Steigerung",
    DRAMATURGY_ROLE_CLIMAX: "Höhepunkt",
    DRAMATURGY_ROLE_RESOLUTION: "Ausklang",
}
DRAMATURGY_STATUS_DRAFT = "DRAFT"
DRAMATURGY_STATUS_CONFIRMED = "CONFIRMED"

# --- Folder Voice-overs (Phase 4) ---
MAX_VOICEOVER_REVIEW_ATTEMPTS = 3
WEAK_ASSET_MATCH_CONFIDENCE_THRESHOLD = 0.4

FACTUALITY_MODE_STRICT_INVENTORY_ONLY = "strict_inventory_only"
FACTUALITY_MODE_NORMAL_SAFE_GENERAL_KNOWLEDGE = "normal_safe_general_knowledge"
FACTUALITY_MODE_ATMOSPHERIC_NO_HARD_FACTS = "atmospheric_no_hard_facts"
FACTUALITY_MODE_CHOICES = (
    FACTUALITY_MODE_STRICT_INVENTORY_ONLY,
    FACTUALITY_MODE_NORMAL_SAFE_GENERAL_KNOWLEDGE,
    FACTUALITY_MODE_ATMOSPHERIC_NO_HARD_FACTS,
)
FACTUALITY_MODE_LABELS = {
    FACTUALITY_MODE_STRICT_INVENTORY_ONLY: "Nur Inventory (streng)",
    FACTUALITY_MODE_NORMAL_SAFE_GENERAL_KNOWLEDGE: "Normal (sicheres Allgemeinwissen)",
    FACTUALITY_MODE_ATMOSPHERIC_NO_HARD_FACTS: "Atmosphärisch (keine harten Fakten)",
}

ENERGY_CALM = "calm"
ENERGY_MEDIUM = "medium"
ENERGY_HIGH = "high"
ENERGY_CHOICES = (ENERGY_CALM, ENERGY_MEDIUM, ENERGY_HIGH)
ENERGY_LABELS = {
    ENERGY_CALM: "Ruhig",
    ENERGY_MEDIUM: "Mittel",
    ENERGY_HIGH: "Energiegeladen",
}

VOICEOVER_STATUS_DRAFT = "DRAFT"
VOICEOVER_STATUS_NEEDS_VALIDATION = "NEEDS_VALIDATION"
VOICEOVER_STATUS_PASS = "PASS"
VOICEOVER_STATUS_NEEDS_USER_REVIEW = "NEEDS_USER_REVIEW"
VOICEOVER_STATUS_CONFIRMED = "CONFIRMED"
VOICEOVER_STATUS_PARTIAL = "PARTIAL"
VOICEOVER_STATUS_UNKNOWN = "UNKNOWN"
VOICEOVER_SETTING_STATUS_PENDING = "PENDING"

# Fehlertypen: deterministisch (Python) vs. LLM-Review (weiche Kriterien) — Phase 4 §8.
VO_ERROR_WORD_COUNT_OUT_OF_RANGE = "WORD_COUNT_OUT_OF_RANGE"
VO_ERROR_LANGUAGE_MISMATCH = "LANGUAGE_MISMATCH"
VO_ERROR_FORBIDDEN_TERM_USED = "FORBIDDEN_TERM_USED"
VO_ERROR_GLOBAL_NEGATIVE_RULE_VIOLATED = "GLOBAL_NEGATIVE_RULE_VIOLATED"
VO_ERROR_FOLDER_NEGATIVE_RULE_VIOLATED = "FOLDER_NEGATIVE_RULE_VIOLATED"
VO_ERROR_HALLUCINATED_FACT = "HALLUCINATED_FACT"
VO_ERROR_TOO_GENERIC = "TOO_GENERIC"
VO_ERROR_TOO_ASSET_DESCRIPTIVE = "TOO_ASSET_DESCRIPTIVE"
VO_ERROR_MISSING_TRANSITION = "MISSING_TRANSITION"
VO_ERROR_MISSING_CONTRAST_OR_COMMONALITY = "MISSING_CONTRAST_OR_COMMONALITY"
VO_ERROR_DOES_NOT_MATCH_ASSETS = "DOES_NOT_MATCH_ASSETS"
VO_ERROR_MISSING_ASSET_MAPPING = "MISSING_ASSET_MAPPING"
VO_ERROR_INVALID_ASSET_ID = "INVALID_ASSET_ID"
VO_ERROR_WEAK_ASSET_MATCH = "WEAK_ASSET_MATCH"
VO_ERROR_MISSING_SUPPLEMENT_REASON = "MISSING_SUPPLEMENT_REASON"
VO_ERROR_REPETITIVE_PHRASING = "REPETITIVE_PHRASING"
VO_ERROR_STYLE_PROFILE_MISMATCH = "STYLE_PROFILE_MISMATCH"
VO_ERROR_UNKNOWN_LLM_REVIEW_ERROR = "UNKNOWN_LLM_REVIEW_ERROR"

# Phase 5: zusätzliche Risiko-Typen für die Intro-Hook-Asset-Validierung
# (INVALID_ASSET_ID, MISSING_ASSET_MAPPING, MISSING_SUPPLEMENT_REASON,
# WEAK_ASSET_MATCH, WORD_COUNT_OUT_OF_RANGE, FORBIDDEN_TERM_USED werden von
# den Phase-4-VO_ERROR_*-Konstanten wiederverwendet).
VO_ERROR_INVALID_FOLDER_REFERENCE = "INVALID_FOLDER_REFERENCE"
VO_ERROR_INVALID_SENTENCE_REFERENCE = "INVALID_SENTENCE_REFERENCE"

VO_ERROR_TYPES_DETERMINISTIC = (
    VO_ERROR_WORD_COUNT_OUT_OF_RANGE,
    VO_ERROR_FORBIDDEN_TERM_USED,
    VO_ERROR_INVALID_ASSET_ID,
    VO_ERROR_MISSING_ASSET_MAPPING,
    VO_ERROR_MISSING_SUPPLEMENT_REASON,
    VO_ERROR_WEAK_ASSET_MATCH,
    VO_ERROR_MISSING_TRANSITION,
    VO_ERROR_MISSING_CONTRAST_OR_COMMONALITY,
)
VO_ERROR_TYPES_LLM_REVIEW = (
    VO_ERROR_LANGUAGE_MISMATCH,
    VO_ERROR_GLOBAL_NEGATIVE_RULE_VIOLATED,
    VO_ERROR_FOLDER_NEGATIVE_RULE_VIOLATED,
    VO_ERROR_HALLUCINATED_FACT,
    VO_ERROR_TOO_GENERIC,
    VO_ERROR_TOO_ASSET_DESCRIPTIVE,
    VO_ERROR_DOES_NOT_MATCH_ASSETS,
    VO_ERROR_REPETITIVE_PHRASING,
    VO_ERROR_STYLE_PROFILE_MISMATCH,
)
VO_ERROR_TYPES_ALL = VO_ERROR_TYPES_DETERMINISTIC + VO_ERROR_TYPES_LLM_REVIEW

# --- Intro Hook (Phase 5) ---
INTRO_HOOK_SETTINGS_FILENAME = "intro_hook_settings.json"
INTRO_HOOK_DEFAULT_TARGET_WORDS = 70
INTRO_HOOK_DEFAULT_MIN_WORDS = 60
INTRO_HOOK_DEFAULT_MAX_WORDS = 80
INTRO_HOOK_CANDIDATE_COUNT = 5
INTRO_HOOK_TYPE_MYSTERY = "mystery"
INTRO_HOOK_TYPE_CONTRAST = "contrast"
INTRO_HOOK_TYPE_SURPRISE = "surprise"
INTRO_HOOK_TYPE_CINEMATIC_PROMISE = "cinematic_promise"
INTRO_HOOK_TYPE_QUESTION = "question"
INTRO_HOOK_TYPE_EMOTIONAL = "emotional"
INTRO_HOOK_TYPES = (
    INTRO_HOOK_TYPE_MYSTERY,
    INTRO_HOOK_TYPE_CONTRAST,
    INTRO_HOOK_TYPE_SURPRISE,
    INTRO_HOOK_TYPE_CINEMATIC_PROMISE,
    INTRO_HOOK_TYPE_QUESTION,
    INTRO_HOOK_TYPE_EMOTIONAL,
)
INTRO_HOOK_STATUS_DRAFT = "DRAFT"
INTRO_HOOK_STATUS_READY = "READY"
INTRO_HOOK_STATUS_PARSE_FAILED = "PARSE_FAILED"
INTRO_HOOK_STATUS_FAIL = "FAIL"
INTRO_HOOK_STATUS_CONFIRMED = "CONFIRMED"

# --- ElevenLabs Audio/TTS (Phase 6) ---
ELEVENLABS_MODEL_PRESETS = (
    "eleven_multilingual_v2",
    "eleven_turbo_v2_5",
    "eleven_flash_v2_5",
    "eleven_v3",
)
ELEVENLABS_DEFAULT_MODEL_ID = "eleven_multilingual_v2"
ELEVENLABS_DEFAULT_OUTPUT_FORMAT = "mp3_44100_128"
ELEVENLABS_API_BASE_URL = "https://api.elevenlabs.io/v1"

AUDIO_ALIGNMENT_FILENAME = "voiceover_alignment.json"
TTS_RUN_MANIFEST_FILENAME = "tts_run_manifest.json"
ELEVENLABS_TTS_REQUEST_METADATA_FILENAME = "elevenlabs_tts_request_metadata.json"
ELEVENLABS_TTS_RESPONSE_METADATA_FILENAME = "elevenlabs_tts_response_metadata.json"
ELEVENLABS_TIMESTAMPS_FILENAME = "elevenlabs_timestamps.json"
TTS_ERRORS_FILENAME = "tts_errors.json"
AUDIO_TEST_SUBDIR = "_test"

AUDIO_SCOPE_INTRO = "intro"
AUDIO_SCOPE_FOLDER = "folder"

AUDIO_STATUS_READY = "AUDIO_READY"
AUDIO_STATUS_READY_WITH_WARNINGS = "AUDIO_READY_WITH_WARNINGS"
AUDIO_STATUS_STALE = "STALE"
AUDIO_STATUS_FAILED = "FAILED"
AUDIO_STATUS_MISSING = "MISSING"

TTS_RUN_STATUS_PASS = "PASS"
TTS_RUN_STATUS_FAIL = "FAIL"

ALIGNMENT_SOURCE_ELEVENLABS_TIMESTAMPS = "elevenlabs_timestamps"

ALIGNMENT_WARNING_TEXT_SEGMENT_NOT_FOUND = "TEXT_SEGMENT_NOT_FOUND"
ALIGNMENT_WARNING_USED_PROPORTIONAL_FALLBACK = "USED_PROPORTIONAL_FALLBACK"
ALIGNMENT_WARNING_MISSING_CHARACTER_TIMESTAMPS = "MISSING_CHARACTER_TIMESTAMPS"
ALIGNMENT_WARNING_NON_MONOTONIC_TIMESTAMPS = "NON_MONOTONIC_TIMESTAMPS"
ALIGNMENT_WARNING_AUDIO_DURATION_MISMATCH = "AUDIO_DURATION_MISMATCH"
ALIGNMENT_WARNING_EMPTY_SEGMENT_TEXT = "EMPTY_SEGMENT_TEXT"
ALIGNMENT_WARNING_AUDIO_DURATION_UNKNOWN = "AUDIO_DURATION_UNKNOWN"

# --- Final Output / confirmed_voiceover_project_plan (Phase 7) ---
PLAN_STATUS_TEXT_READY = "TEXT_READY"
PLAN_STATUS_AUDIO_PENDING = "AUDIO_PENDING"
PLAN_STATUS_AUDIO_READY = "AUDIO_READY"
PLAN_STATUS_READY_FOR_CUT = "READY_FOR_CUT"
PLAN_STATUS_NEEDS_REVIEW = "NEEDS_REVIEW"

ITEM_READINESS_READY = "READY"
ITEM_READINESS_MISSING_AUDIO = "MISSING_AUDIO"
ITEM_READINESS_MISSING_ALIGNMENT = "MISSING_ALIGNMENT"
ITEM_READINESS_STALE_AUDIO = "STALE_AUDIO"
ITEM_READINESS_WARNING = "WARNING"
ITEM_READINESS_BLOCKED = "BLOCKED"

ASSET_MAPPING_STATUS_PASS = "PASS"
ASSET_MAPPING_STATUS_WARNINGS = "WARNINGS"
ASSET_MAPPING_STATUS_BLOCKED = "BLOCKED"

READINESS_ERROR_MISSING_CONFIRMED_DRAMATURGY = "MISSING_CONFIRMED_DRAMATURGY"
READINESS_ERROR_MISSING_CONFIRMED_INTRO = "MISSING_CONFIRMED_INTRO"
READINESS_ERROR_MISSING_FOLDER_VOICEOVER = "MISSING_FOLDER_VOICEOVER"
READINESS_ERROR_EMPTY_TEXT = "EMPTY_TEXT"
READINESS_ERROR_EMPTY_SENTENCE_ITEMS = "EMPTY_SENTENCE_ITEMS"
READINESS_ERROR_EMPTY_VISUAL_BEATS = "EMPTY_VISUAL_BEATS"
READINESS_ERROR_MISSING_AUDIO = "MISSING_AUDIO"
READINESS_ERROR_MISSING_ALIGNMENT = "MISSING_ALIGNMENT"
READINESS_ERROR_AUDIO_FAILED = "AUDIO_FAILED"
READINESS_ERROR_AUDIO_STALE = "AUDIO_STALE"
READINESS_ERROR_AUDIO_DURATION_MISSING = "AUDIO_DURATION_MISSING"
READINESS_ERROR_NEEDS_USER_REVIEW = "NEEDS_USER_REVIEW"
READINESS_ERROR_PLAN_STALE = "PLAN_STALE"

READINESS_SEVERITY_WARNING = "WARNING"
READINESS_SEVERITY_BLOCKER = "BLOCKER"
MODEL_COMPARISON_SUBDIR = "model_comparison_runs"
MODEL_COMPARISON_SUMMARY_FILENAME = "model_comparison_summary.json"
MODEL_COMPARISON_PRESETS: dict[str, tuple[str, ...]] = {
    "gemini": ("gemini-3.1-pro-preview", "gemini-3.1-flash-lite"),
    "anthropic": ("anthropic:claude-sonnet-5", "anthropic:claude-opus-4-8"),
    "openai": ("openai:gpt-5.5", "openai:gpt-5.4-mini"),
}
EXPORTS_SUBDIR = "exports"
CLEAN_MEDIA_OUTPUT_SUBDIR = "clean"
CLEAN_MEDIA_MANIFEST_SUBDIR = "clean_media"
DEFAULT_SHOT_MIN_SEC = 3.0
DEFAULT_SHOT_MAX_SEC = 8.0
DEFAULT_AUDIO_OFFSET_SEC = 1.0
DEFAULT_SECTION_OUTRO_SEC = 5.0
MAX_GEMINI_PLAN_ATTEMPTS = 3
OUTRO_BEAT_ID = "outro_001"
DEFAULT_TEXT_SPLITTERS = (", und ", ", ", " und ")
FALLBACK_SOURCE_LOCAL = "local"
FALLBACK_SOURCE_MISSING = "missing"
FALLBACK_SOURCE_ADOBE_STOCK = "adobe_stock"
FALLBACK_SOURCE_PEXELS = "pexels"
FALLBACK_SOURCE_GEMINI_IMAGE = "gemini_image"
FALLBACK_SOURCE_CHOICES = (
    FALLBACK_SOURCE_LOCAL,
    FALLBACK_SOURCE_ADOBE_STOCK,
    FALLBACK_SOURCE_PEXELS,
    FALLBACK_SOURCE_GEMINI_IMAGE,
)
FALLBACK_SOURCE_LABELS = {
    FALLBACK_SOURCE_LOCAL: "Lokale Assets",
    FALLBACK_SOURCE_ADOBE_STOCK: "Adobe Stock",
    FALLBACK_SOURCE_PEXELS: "Pexels & Co.",
    FALLBACK_SOURCE_GEMINI_IMAGE: "KI-Bild (Gemini)",
}
DEFAULT_FALLBACK_ORDER = (
    FALLBACK_SOURCE_LOCAL,
    FALLBACK_SOURCE_ADOBE_STOCK,
    FALLBACK_SOURCE_PEXELS,
    FALLBACK_SOURCE_GEMINI_IMAGE,
)

SUPPLEMENT_SUBDIR = "supplement"
SUPPLEMENT_REQUESTS_FILENAME = "supplement_requests.json"
SUPPLEMENT_MANIFEST_FILENAME = "supplement_manifest.json"
SUPPLEMENT_ERRORS_FILENAME = "supplement_errors.json"
PEXELS_DEBUG_REPORT_FILENAME = "pexels_debug_report.json"
INVENTORY_DELTA_SUFFIX = ".inventory_delta.json"
SUPPLEMENTAL_FOLDER_NAME = "_supplemental"
DEFAULT_COVERAGE_THRESHOLD = 0.55

MATCH_QUALITY_SEHR_GUT = "sehr_gut"
MATCH_QUALITY_GUT = "gut"
MATCH_QUALITY_MITTEL = "mittel"
MATCH_QUALITY_UNPASSEND = "unpassend"

MATCH_QUALITY_CHOICES = (
    MATCH_QUALITY_SEHR_GUT,
    MATCH_QUALITY_GUT,
    MATCH_QUALITY_MITTEL,
    MATCH_QUALITY_UNPASSEND,
)

MATCH_QUALITY_LABELS = {
    MATCH_QUALITY_SEHR_GUT: "Sehr gut",
    MATCH_QUALITY_GUT: "Gut",
    MATCH_QUALITY_MITTEL: "Mittel",
    MATCH_QUALITY_UNPASSEND: "Unpassend",
}

PROVIDER_STATUS_MOCK = "MOCK"
PROVIDER_STATUS_CONFIG_MISSING = "CONFIG_MISSING"
PROVIDER_STATUS_READY = "READY"
PROVIDER_STATUS_ERROR = "ERROR"

CANDIDATE_STATUS_FOUND = "CANDIDATE_FOUND"
CANDIDATE_STATUS_MOCK_ONLY = "CANDIDATE_MOCK_ONLY"
CANDIDATE_STATUS_SELECTED = "SELECTED"
CANDIDATE_STATUS_ACQUIRE_STARTED = "ACQUIRE_STARTED"
CANDIDATE_STATUS_ACQUIRED = "ACQUIRED"
CANDIDATE_STATUS_DOWNLOAD_FAILED = "DOWNLOAD_FAILED"
CANDIDATE_STATUS_REJECTED_ASPECT_RATIO = "REJECTED_ASPECT_RATIO"
CANDIDATE_STATUS_NOT_DOWNLOADABLE_16_9 = "NOT_DOWNLOADABLE_16_9"
CANDIDATE_STATUS_GENERATION_FAILED = "GENERATION_FAILED"
CANDIDATE_STATUS_IMPORTED_MANUALLY = "IMPORTED_MANUALLY"
CANDIDATE_STATUS_ANALYSIS_PENDING = "ANALYSIS_PENDING"
CANDIDATE_STATUS_ANALYSIS_COMPLETE = "ANALYSIS_COMPLETE"
CANDIDATE_STATUS_INVENTORY_ADDED = "INVENTORY_ADDED"

REQUEST_STATUS_PENDING_SOURCE = "PENDING_SOURCE_SELECTION"
REQUEST_STATUS_SOURCE_SELECTED = "SOURCE_SELECTED"
REQUEST_STATUS_CANDIDATES_FOUND = "CANDIDATES_FOUND"
REQUEST_STATUS_AWAITING_SELECTION = "AWAITING_USER_SELECTION"
REQUEST_STATUS_ACQUIRE_FAILED = "ACQUIRE_FAILED"
REQUEST_STATUS_ASSET_ACQUIRED = "ASSET_ACQUIRED"
REQUEST_STATUS_ANALYSIS_PENDING = "ANALYSIS_PENDING"
REQUEST_STATUS_INVENTORY_UPDATED = "INVENTORY_UPDATED"
REQUEST_STATUS_READY_FOR_REPLAN = "READY_FOR_REPLAN"

SUPPLEMENT_SOURCE_ADOBE = "adobe_stock"
SUPPLEMENT_SOURCE_PEXELS = "pexels"
SUPPLEMENT_SOURCE_GOOGLE = "google_search"
SUPPLEMENT_SOURCE_NANO_BANANA = "nano_banana"
SUPPLEMENT_SOURCE_MANUAL = "manual"

SUPPLEMENT_SOURCE_LABELS = {
    SUPPLEMENT_SOURCE_ADOBE: "Adobe Stock",
    SUPPLEMENT_SOURCE_PEXELS: "Pexels",
    SUPPLEMENT_SOURCE_GOOGLE: "Google Suche",
    SUPPLEMENT_SOURCE_NANO_BANANA: "Nano Banana / KI-Bild",
    SUPPLEMENT_SOURCE_MANUAL: "Manuell später",
}

ASSET_ORIGIN_LOCAL = "local_original"
ASSET_ORIGIN_ADOBE = "adobe_stock"
ASSET_ORIGIN_PEXELS = "pexels"
ASSET_ORIGIN_GOOGLE = "google_search"
ASSET_ORIGIN_NANO_BANANA = "nano_banana"
ASSET_ORIGIN_MANUAL = "manual"

RIGHTS_STATUS_APPROVED = "APPROVED"
RIGHTS_STATUS_NEEDS_LICENSE_REVIEW = "NEEDS_LICENSE_REVIEW"
RIGHTS_STATUS_GENERATED_APPROVED = "GENERATED_APPROVED"
RIGHTS_STATUS_NEEDS_REVIEW = "NEEDS_REVIEW"


def resolve_voice_backend(backend: str | None) -> str:
    if backend and backend.strip() in VOICE_BACKEND_CHOICES:
        return backend.strip()
    return DEFAULT_VOICE_BACKEND


def resolve_whisper_model(model: str | None) -> str:
    if model and model.strip() in WHISPER_MODEL_CHOICES:
        return model.strip()
    return DEFAULT_WHISPER_MODEL
