"""Zentrale Standardwerte — unabhängig von Pfad- und DB-Konfiguration."""

from __future__ import annotations

DEFAULT_WORK_SUBDIR = "_otio"
DEFAULT_VOICE_OVER_SUBDIR = "Voice over"
DEFAULT_FRAMES_PER_SHOT = 3
DEFAULT_GEMINI_MODEL = "gemini-3.1-flash-lite"
DEFAULT_VOICE_BACKEND = "whisper"
DEFAULT_WHISPER_MODEL = "large-v3"
VOICE_BACKEND_WHISPER = "whisper"
VOICE_BACKEND_GEMINI = "gemini"
VOICE_BACKEND_CHOICES = (
    VOICE_BACKEND_WHISPER,
    VOICE_BACKEND_GEMINI,
)
VOICE_BACKEND_LABELS = {
    VOICE_BACKEND_WHISPER: "Whisper (lokal, kostenlos)",
    VOICE_BACKEND_GEMINI: "Gemini (Cloud, kostenpflichtig)",
}
WHISPER_MODEL_CHOICES = (
    "tiny",
    "base",
    "small",
    "medium",
    "large-v3",
)
WHISPER_MODEL_LABELS = {
    "tiny": "Whisper tiny — am schnellsten, grober",
    "base": "Whisper base — schnell",
    "small": "Whisper small — schnell, ausgewogen",
    "medium": "Whisper medium — genauer, langsamer",
    "large-v3": "Whisper large-v3 — beste Qualität, am langsamsten (Standard)",
}
GEMINI_MODEL_CHOICES = (
    "gemini-3-flash-preview",
    "gemini-3.1-flash-lite",
    "gemini-3.1-pro-preview",
)
GEMINI_MODEL_LABELS = {
    "gemini-3-flash-preview": "Gemini 3 Flash Preview — schnell, Pro-Niveau (Preview)",
    "gemini-3.1-flash-lite": "Gemini 3.1 Flash Lite — günstig, Preview (Standard)",
    "gemini-3.1-pro-preview": "Gemini 3.1 Pro Preview — beste Qualität (Preview, teurer)",
}

OPENAI_PLAN_MODEL_CHOICES = (
    "openai:gpt-5.5",
    "openai:gpt-5.4-mini",
)
ANTHROPIC_PLAN_MODEL_CHOICES = (
    "anthropic:claude-opus-4-8",
    "anthropic:claude-sonnet-5",
)
EDIT_PLAN_MODEL_CHOICES = GEMINI_MODEL_CHOICES + OPENAI_PLAN_MODEL_CHOICES + ANTHROPIC_PLAN_MODEL_CHOICES
EDIT_PLAN_MODEL_LABELS = {
    **GEMINI_MODEL_LABELS,
    "openai:gpt-5.5": "ChatGPT GPT-5.5 — Flagship, beste Qualität",
    "openai:gpt-5.4-mini": "ChatGPT GPT-5.4 mini — günstig, schnell",
    "anthropic:claude-opus-4-8": "Claude Opus 4.8 — Flagship, beste Qualität",
    "anthropic:claude-sonnet-5": "Claude Sonnet 5 — ausgewogen, günstiger",
}
INVENTORY_FILENAME = "inventory.json"
INVENTORY_SUBDIR = "inventory"
MANUAL_FOLDER_COMPLETION_FILENAME = "manual_folder_completion.json"
VOICE_ANALYSIS_FILENAME = "voice_over_analysis.json"
VOICE_FOLDER_MAPPING_FILENAME = "voice_folder_mapping.json"
EDIT_PLAN_FILENAME = "edit_plan.json"
EDIT_PLAN_SUBDIR = "edit_plan"

PROJECT_MODE_WITH_VOICEOVER = "with_voiceover"
PROJECT_MODE_WITHOUT_VOICEOVER = "without_voiceover"
PROJECT_MODE_CHOICES = (PROJECT_MODE_WITH_VOICEOVER, PROJECT_MODE_WITHOUT_VOICEOVER)
PROJECT_MODE_LABELS = {
    PROJECT_MODE_WITH_VOICEOVER: "Projekt mit Voice-Over",
    PROJECT_MODE_WITHOUT_VOICEOVER: "Projekt ohne Voice-Over",
}

VOICEOVER_GENERATION_SUBDIR = "voiceover_generation"
VOICEOVER_GENERATION_LLM_RUNS_SUBDIR = "llm_runs"
VOICEOVER_GENERATION_AUDIO_SUBDIR = "audio"
VOICEOVER_GENERATION_TTS_RUNS_SUBDIR = "tts_runs"
VOICEOVER_GENERATION_INTRO_AUDIO_FOLDER_NAME = "000_intro"
STYLE_REFERENCES_SUBDIR = "style_references"
STYLE_REFERENCES_UPLOADS_SUBDIR = "uploads"
MODEL_SETTINGS_FILENAME = "model_settings.json"

PROJECT_BRIEF_FILENAME = "project_brief.json"
VOICEOVER_STYLE_REFERENCES_FILENAME = "voiceover_style_references.json"
VOICEOVER_STYLE_PROFILE_FILENAME = "voiceover_style_profile.json"
DRAMATURGY_PLAN_DRAFT_FILENAME = "dramaturgy_plan.draft.json"
DRAMATURGY_PLAN_CONFIRMED_FILENAME = "dramaturgy_plan.confirmed.json"
FOLDER_VOICEOVER_SETTINGS_FILENAME = "folder_voiceover_settings.json"
FOLDER_VOICEOVERS_DRAFT_FILENAME = "folder_voiceovers.draft.json"
FOLDER_VOICEOVER_VALIDATION_REPORT_FILENAME = "folder_voiceover_validation_report.json"
FOLDER_VOICEOVERS_CONFIRMED_FILENAME = "folder_voiceovers.confirmed.json"
INTRO_HOOK_CANDIDATES_FILENAME = "intro_hook_candidates.json"
INTRO_HOOK_CONFIRMED_FILENAME = "intro_hook.confirmed.json"
ELEVENLABS_SETTINGS_FILENAME = "elevenlabs_settings.json"
VOICEOVER_AUDIO_MANIFEST_FILENAME = "voiceover_audio_manifest.json"
VOICEOVER_AUDIO_QA_REPORT_FILENAME = "voiceover_audio_qa_report.json"
CONFIRMED_VOICEOVER_PROJECT_PLAN_FILENAME = "confirmed_voiceover_project_plan.json"
VOICEOVER_PROJECT_PLAN_JSON_FILENAME = "voiceover_project_plan.json"
VOICEOVER_PROJECT_PLAN_MD_FILENAME = "voiceover_project_plan.md"
VOICEOVER_PROJECT_PLAN_CSV_FILENAME = "voiceover_project_plan.csv"

# --- LLM-Provider/Modell-Presets für die Voice-over-Generierungs-Pipeline ---
# Eigenständig von EDIT_PLAN_MODEL_CHOICES: hier werden provider und model als
# getrennte Felder gespeichert (siehe VoiceoverGenerationModelSettings), daher
# ohne "anthropic:"/"openai:"-Präfix.
VOICEOVER_GEN_PROVIDERS = ("anthropic", "openai", "gemini")
VOICEOVER_GEN_MODEL_PRESETS: dict[str, tuple[str, ...]] = {
    "anthropic": ("claude-opus-4-8", "claude-sonnet-5", "claude-haiku-4-5"),
    "openai": ("gpt-5.5", "gpt-5.4-mini"),
    "gemini": ("gemini-3.1-pro-preview", "gemini-3.1-flash-lite"),
}
VOICEOVER_GEN_ROLE_STYLE_PROFILE = "style_profile"
VOICEOVER_GEN_ROLE_DRAMATURGY = "dramaturgy"
VOICEOVER_GEN_ROLE_VOICEOVER_AUTHOR = "voiceover_author"
VOICEOVER_GEN_ROLE_VOICEOVER_REVIEW = "voiceover_review"
VOICEOVER_GEN_ROLE_INTRO = "intro"
VOICEOVER_GEN_ROLES = (
    VOICEOVER_GEN_ROLE_STYLE_PROFILE,
    VOICEOVER_GEN_ROLE_DRAMATURGY,
    VOICEOVER_GEN_ROLE_VOICEOVER_AUTHOR,
    VOICEOVER_GEN_ROLE_VOICEOVER_REVIEW,
    VOICEOVER_GEN_ROLE_INTRO,
)
VOICEOVER_GEN_ROLE_LABELS = {
    VOICEOVER_GEN_ROLE_STYLE_PROFILE: "Style Profile",
    VOICEOVER_GEN_ROLE_DRAMATURGY: "Dramaturgie",
    VOICEOVER_GEN_ROLE_VOICEOVER_AUTHOR: "Voice-over Autor",
    VOICEOVER_GEN_ROLE_VOICEOVER_REVIEW: "Voice-over Review",
    VOICEOVER_GEN_ROLE_INTRO: "Intro",
}
VOICEOVER_GEN_DEFAULT_PROVIDER = "anthropic"
VOICEOVER_GEN_DEFAULT_MODEL = "claude-sonnet-5"

# --- Project Brief: feste Auswahllisten ---
BRIEF_LANGUAGE_CHOICES = ("DE", "EN", "FR", "ES", "PT", "IT")
BRIEF_TONE_TAG_CHOICES = (
    "cinematic",
    "documentary",
    "discovery",
    "calm",
    "dramatic",
    "premium travel",
    "mysterious",
    "energetic",
    "poetic but factual",
    "high-end YouTube documentary",
)
BRIEF_NEGATIVE_RULE_NO_INVENTED_FACTS = "no_invented_facts"
BRIEF_NEGATIVE_RULE_NO_EXAGGERATED_SUPERLATIVES = "no_exaggerated_superlatives"
BRIEF_NEGATIVE_RULE_NO_CLICKBAIT_PHRASES = "no_clickbait_phrases"
BRIEF_NEGATIVE_RULE_NO_REPETITION = "no_repetition"
BRIEF_NEGATIVE_RULE_NO_DIRECT_VIEWER_ADDRESS = "no_direct_viewer_address"
BRIEF_NEGATIVE_RULE_NO_IN_THIS_VIDEO_PHRASING = "no_in_this_video_phrasing"
BRIEF_NEGATIVE_RULE_NO_UNVERIFIED_HISTORICAL_CLAIMS = "no_unverified_historical_claims"
BRIEF_NEGATIVE_RULE_NOT_JUST_ASSET_DESCRIPTIONS = "not_just_asset_descriptions"
BRIEF_NEGATIVE_RULE_DOCUMENTARY_PROSE_REQUIRED = "documentary_prose_required"
BRIEF_NEGATIVE_RULE_FLAGS = (
    BRIEF_NEGATIVE_RULE_NO_INVENTED_FACTS,
    BRIEF_NEGATIVE_RULE_NO_EXAGGERATED_SUPERLATIVES,
    BRIEF_NEGATIVE_RULE_NO_CLICKBAIT_PHRASES,
    BRIEF_NEGATIVE_RULE_NO_REPETITION,
    BRIEF_NEGATIVE_RULE_NO_DIRECT_VIEWER_ADDRESS,
    BRIEF_NEGATIVE_RULE_NO_IN_THIS_VIDEO_PHRASING,
    BRIEF_NEGATIVE_RULE_NO_UNVERIFIED_HISTORICAL_CLAIMS,
    BRIEF_NEGATIVE_RULE_NOT_JUST_ASSET_DESCRIPTIONS,
    BRIEF_NEGATIVE_RULE_DOCUMENTARY_PROSE_REQUIRED,
)
BRIEF_NEGATIVE_RULE_LABELS = {
    BRIEF_NEGATIVE_RULE_NO_INVENTED_FACTS: "Keine erfundenen Fakten",
    BRIEF_NEGATIVE_RULE_NO_EXAGGERATED_SUPERLATIVES: "Keine übertriebenen Superlative",
    BRIEF_NEGATIVE_RULE_NO_CLICKBAIT_PHRASES: "Keine Clickbait-Floskeln",
    BRIEF_NEGATIVE_RULE_NO_REPETITION: "Keine Wiederholungen",
    BRIEF_NEGATIVE_RULE_NO_DIRECT_VIEWER_ADDRESS: "Keine direkte Zuschaueransprache",
    BRIEF_NEGATIVE_RULE_NO_IN_THIS_VIDEO_PHRASING: 'Keine Formulierungen wie "in diesem Video"',
    BRIEF_NEGATIVE_RULE_NO_UNVERIFIED_HISTORICAL_CLAIMS: "Keine unbelegten historischen Behauptungen",
    BRIEF_NEGATIVE_RULE_NOT_JUST_ASSET_DESCRIPTIONS: "Nicht nur Assetbeschreibungen",
    BRIEF_NEGATIVE_RULE_DOCUMENTARY_PROSE_REQUIRED: "Text muss wie echte Doku-Prosa klingen",
}
DEFAULT_NEGATIVE_RULE_FLAGS: dict[str, bool] = {flag: True for flag in BRIEF_NEGATIVE_RULE_FLAGS}

# --- Dramaturgie: Wortanzahl-Heuristik pro Ordner (Phase 3) ---
# Ausgangsheuristik — soll später in der UI pro Projekt überschreibbar sein.
VOICEOVER_GEN_DEFAULT_WORD_TOLERANCE_PERCENT = 10
VOICEOVER_GEN_MIN_FOLDER_WORDS = 50
VOICEOVER_GEN_MAX_FOLDER_WORDS = 180

FOLDER_INVENTORY_SUMMARIES_FILENAME = "folder_inventory_summaries.json"

DRAMATURGY_ROLE_OPENER = "opener"
DRAMATURGY_ROLE_SETUP = "setup"
DRAMATURGY_ROLE_CONTRAST = "contrast"
DRAMATURGY_ROLE_ESCALATION = "escalation"
DRAMATURGY_ROLE_CLIMAX = "climax"
DRAMATURGY_ROLE_RESOLUTION = "resolution"
DRAMATURGY_ROLES = (
    DRAMATURGY_ROLE_OPENER,
    DRAMATURGY_ROLE_SETUP,
    DRAMATURGY_ROLE_CONTRAST,
    DRAMATURGY_ROLE_ESCALATION,
    DRAMATURGY_ROLE_CLIMAX,
    DRAMATURGY_ROLE_RESOLUTION,
)
DRAMATURGY_ROLE_LABELS = {
    DRAMATURGY_ROLE_OPENER: "Opener",
    DRAMATURGY_ROLE_SETUP: "Setup",
    DRAMATURGY_ROLE_CONTRAST: "Kontrast",
    DRAMATURGY_ROLE_ESCALATION: "Steigerung",
    DRAMATURGY_ROLE_CLIMAX: "Höhepunkt",
    DRAMATURGY_ROLE_RESOLUTION: "Ausklang",
}
DRAMATURGY_STATUS_DRAFT = "DRAFT"
DRAMATURGY_STATUS_CONFIRMED = "CONFIRMED"

# --- Folder Voice-overs (Phase 4) ---
MAX_VOICEOVER_REVIEW_ATTEMPTS = 3
WEAK_ASSET_MATCH_CONFIDENCE_THRESHOLD = 0.4

FACTUALITY_MODE_STRICT_INVENTORY_ONLY = "strict_inventory_only"
FACTUALITY_MODE_NORMAL_SAFE_GENERAL_KNOWLEDGE = "normal_safe_general_knowledge"
FACTUALITY_MODE_ATMOSPHERIC_NO_HARD_FACTS = "atmospheric_no_hard_facts"
FACTUALITY_MODE_CHOICES = (
    FACTUALITY_MODE_STRICT_INVENTORY_ONLY,
    FACTUALITY_MODE_NORMAL_SAFE_GENERAL_KNOWLEDGE,
    FACTUALITY_MODE_ATMOSPHERIC_NO_HARD_FACTS,
)
FACTUALITY_MODE_LABELS = {
    FACTUALITY_MODE_STRICT_INVENTORY_ONLY: "Nur Inventory (streng)",
    FACTUALITY_MODE_NORMAL_SAFE_GENERAL_KNOWLEDGE: "Normal (sicheres Allgemeinwissen)",
    FACTUALITY_MODE_ATMOSPHERIC_NO_HARD_FACTS: "Atmosphärisch (keine harten Fakten)",
}

ENERGY_CALM = "calm"
ENERGY_MEDIUM = "medium"
ENERGY_HIGH = "high"
ENERGY_CHOICES = (ENERGY_CALM, ENERGY_MEDIUM, ENERGY_HIGH)
ENERGY_LABELS = {
    ENERGY_CALM: "Ruhig",
    ENERGY_MEDIUM: "Mittel",
    ENERGY_HIGH: "Energiegeladen",
}

VOICEOVER_STATUS_DRAFT = "DRAFT"
VOICEOVER_STATUS_NEEDS_VALIDATION = "NEEDS_VALIDATION"
VOICEOVER_STATUS_PASS = "PASS"
VOICEOVER_STATUS_NEEDS_USER_REVIEW = "NEEDS_USER_REVIEW"
VOICEOVER_STATUS_CONFIRMED = "CONFIRMED"
VOICEOVER_STATUS_PARTIAL = "PARTIAL"
VOICEOVER_STATUS_UNKNOWN = "UNKNOWN"
VOICEOVER_SETTING_STATUS_PENDING = "PENDING"

# Fehlertypen: deterministisch (Python) vs. LLM-Review (weiche Kriterien) — Phase 4 §8.
VO_ERROR_WORD_COUNT_OUT_OF_RANGE = "WORD_COUNT_OUT_OF_RANGE"
VO_ERROR_LANGUAGE_MISMATCH = "LANGUAGE_MISMATCH"
VO_ERROR_FORBIDDEN_TERM_USED = "FORBIDDEN_TERM_USED"
VO_ERROR_GLOBAL_NEGATIVE_RULE_VIOLATED = "GLOBAL_NEGATIVE_RULE_VIOLATED"
VO_ERROR_FOLDER_NEGATIVE_RULE_VIOLATED = "FOLDER_NEGATIVE_RULE_VIOLATED"
VO_ERROR_HALLUCINATED_FACT = "HALLUCINATED_FACT"
VO_ERROR_TOO_GENERIC = "TOO_GENERIC"
VO_ERROR_TOO_ASSET_DESCRIPTIVE = "TOO_ASSET_DESCRIPTIVE"
VO_ERROR_MISSING_TRANSITION = "MISSING_TRANSITION"
VO_ERROR_MISSING_CONTRAST_OR_COMMONALITY = "MISSING_CONTRAST_OR_COMMONALITY"
VO_ERROR_DOES_NOT_MATCH_ASSETS = "DOES_NOT_MATCH_ASSETS"
VO_ERROR_MISSING_ASSET_MAPPING = "MISSING_ASSET_MAPPING"
VO_ERROR_INVALID_ASSET_ID = "INVALID_ASSET_ID"
VO_ERROR_WEAK_ASSET_MATCH = "WEAK_ASSET_MATCH"
VO_ERROR_MISSING_SUPPLEMENT_REASON = "MISSING_SUPPLEMENT_REASON"
VO_ERROR_REPETITIVE_PHRASING = "REPETITIVE_PHRASING"
VO_ERROR_STYLE_PROFILE_MISMATCH = "STYLE_PROFILE_MISMATCH"
VO_ERROR_UNKNOWN_LLM_REVIEW_ERROR = "UNKNOWN_LLM_REVIEW_ERROR"

# Phase 5: zusätzliche Risiko-Typen für die Intro-Hook-Asset-Validierung
# (INVALID_ASSET_ID, MISSING_ASSET_MAPPING, MISSING_SUPPLEMENT_REASON,
# WEAK_ASSET_MATCH, WORD_COUNT_OUT_OF_RANGE, FORBIDDEN_TERM_USED werden von
# den Phase-4-VO_ERROR_*-Konstanten wiederverwendet).
VO_ERROR_INVALID_FOLDER_REFERENCE = "INVALID_FOLDER_REFERENCE"
VO_ERROR_INVALID_SENTENCE_REFERENCE = "INVALID_SENTENCE_REFERENCE"

VO_ERROR_TYPES_DETERMINISTIC = (
    VO_ERROR_WORD_COUNT_OUT_OF_RANGE,
    VO_ERROR_FORBIDDEN_TERM_USED,
    VO_ERROR_INVALID_ASSET_ID,
    VO_ERROR_MISSING_ASSET_MAPPING,
    VO_ERROR_MISSING_SUPPLEMENT_REASON,
    VO_ERROR_WEAK_ASSET_MATCH,
    VO_ERROR_MISSING_TRANSITION,
    VO_ERROR_MISSING_CONTRAST_OR_COMMONALITY,
)
VO_ERROR_TYPES_LLM_REVIEW = (
    VO_ERROR_LANGUAGE_MISMATCH,
    VO_ERROR_GLOBAL_NEGATIVE_RULE_VIOLATED,
    VO_ERROR_FOLDER_NEGATIVE_RULE_VIOLATED,
    VO_ERROR_HALLUCINATED_FACT,
    VO_ERROR_TOO_GENERIC,
    VO_ERROR_TOO_ASSET_DESCRIPTIVE,
    VO_ERROR_DOES_NOT_MATCH_ASSETS,
    VO_ERROR_REPETITIVE_PHRASING,
    VO_ERROR_STYLE_PROFILE_MISMATCH,
)
VO_ERROR_TYPES_ALL = VO_ERROR_TYPES_DETERMINISTIC + VO_ERROR_TYPES_LLM_REVIEW

# --- Intro Hook (Phase 5) ---
INTRO_HOOK_SETTINGS_FILENAME = "intro_hook_settings.json"
INTRO_HOOK_DEFAULT_TARGET_WORDS = 70
INTRO_HOOK_DEFAULT_MIN_WORDS = 60
INTRO_HOOK_DEFAULT_MAX_WORDS = 80
INTRO_HOOK_CANDIDATE_COUNT = 5
INTRO_HOOK_TYPE_MYSTERY = "mystery"
INTRO_HOOK_TYPE_CONTRAST = "contrast"
INTRO_HOOK_TYPE_SURPRISE = "surprise"
INTRO_HOOK_TYPE_CINEMATIC_PROMISE = "cinematic_promise"
INTRO_HOOK_TYPE_QUESTION = "question"
INTRO_HOOK_TYPE_EMOTIONAL = "emotional"
INTRO_HOOK_TYPES = (
    INTRO_HOOK_TYPE_MYSTERY,
    INTRO_HOOK_TYPE_CONTRAST,
    INTRO_HOOK_TYPE_SURPRISE,
    INTRO_HOOK_TYPE_CINEMATIC_PROMISE,
    INTRO_HOOK_TYPE_QUESTION,
    INTRO_HOOK_TYPE_EMOTIONAL,
)
INTRO_HOOK_STATUS_DRAFT = "DRAFT"
INTRO_HOOK_STATUS_READY = "READY"
INTRO_HOOK_STATUS_PARSE_FAILED = "PARSE_FAILED"
INTRO_HOOK_STATUS_FAIL = "FAIL"
INTRO_HOOK_STATUS_CONFIRMED = "CONFIRMED"

# --- ElevenLabs Audio/TTS (Phase 6) ---
ELEVENLABS_MODEL_PRESETS = (
    "eleven_multilingual_v2",
    "eleven_turbo_v2_5",
    "eleven_flash_v2_5",
    "eleven_v3",
)
ELEVENLABS_DEFAULT_MODEL_ID = "eleven_multilingual_v2"
ELEVENLABS_DEFAULT_OUTPUT_FORMAT = "mp3_44100_128"
ELEVENLABS_API_BASE_URL = "https://api.elevenlabs.io/v1"

AUDIO_ALIGNMENT_FILENAME = "voiceover_alignment.json"
TTS_RUN_MANIFEST_FILENAME = "tts_run_manifest.json"
ELEVENLABS_TTS_REQUEST_METADATA_FILENAME = "elevenlabs_tts_request_metadata.json"
ELEVENLABS_TTS_RESPONSE_METADATA_FILENAME = "elevenlabs_tts_response_metadata.json"
ELEVENLABS_TIMESTAMPS_FILENAME = "elevenlabs_timestamps.json"
TTS_ERRORS_FILENAME = "tts_errors.json"
AUDIO_TEST_SUBDIR = "_test"

AUDIO_SCOPE_INTRO = "intro"
AUDIO_SCOPE_FOLDER = "folder"

AUDIO_STATUS_READY = "AUDIO_READY"
AUDIO_STATUS_READY_WITH_WARNINGS = "AUDIO_READY_WITH_WARNINGS"
AUDIO_STATUS_STALE = "STALE"
AUDIO_STATUS_FAILED = "FAILED"
AUDIO_STATUS_MISSING = "MISSING"

TTS_RUN_STATUS_PASS = "PASS"
TTS_RUN_STATUS_FAIL = "FAIL"

ALIGNMENT_SOURCE_ELEVENLABS_TIMESTAMPS = "elevenlabs_timestamps"

ALIGNMENT_WARNING_TEXT_SEGMENT_NOT_FOUND = "TEXT_SEGMENT_NOT_FOUND"
ALIGNMENT_WARNING_USED_PROPORTIONAL_FALLBACK = "USED_PROPORTIONAL_FALLBACK"
ALIGNMENT_WARNING_MISSING_CHARACTER_TIMESTAMPS = "MISSING_CHARACTER_TIMESTAMPS"
ALIGNMENT_WARNING_NON_MONOTONIC_TIMESTAMPS = "NON_MONOTONIC_TIMESTAMPS"
ALIGNMENT_WARNING_AUDIO_DURATION_MISMATCH = "AUDIO_DURATION_MISMATCH"
ALIGNMENT_WARNING_EMPTY_SEGMENT_TEXT = "EMPTY_SEGMENT_TEXT"
ALIGNMENT_WARNING_AUDIO_DURATION_UNKNOWN = "AUDIO_DURATION_UNKNOWN"

# --- Final Output / confirmed_voiceover_project_plan (Phase 7) ---
PLAN_STATUS_TEXT_READY = "TEXT_READY"
PLAN_STATUS_AUDIO_PENDING = "AUDIO_PENDING"
PLAN_STATUS_AUDIO_READY = "AUDIO_READY"
PLAN_STATUS_READY_FOR_CUT = "READY_FOR_CUT"
PLAN_STATUS_NEEDS_REVIEW = "NEEDS_REVIEW"

ITEM_READINESS_READY = "READY"
ITEM_READINESS_MISSING_AUDIO = "MISSING_AUDIO"
ITEM_READINESS_MISSING_ALIGNMENT = "MISSING_ALIGNMENT"
ITEM_READINESS_STALE_AUDIO = "STALE_AUDIO"
ITEM_READINESS_WARNING = "WARNING"
ITEM_READINESS_BLOCKED = "BLOCKED"

ASSET_MAPPING_STATUS_PASS = "PASS"
ASSET_MAPPING_STATUS_WARNINGS = "WARNINGS"
ASSET_MAPPING_STATUS_BLOCKED = "BLOCKED"

READINESS_ERROR_MISSING_CONFIRMED_DRAMATURGY = "MISSING_CONFIRMED_DRAMATURGY"
READINESS_ERROR_MISSING_CONFIRMED_INTRO = "MISSING_CONFIRMED_INTRO"
READINESS_ERROR_MISSING_FOLDER_VOICEOVER = "MISSING_FOLDER_VOICEOVER"
READINESS_ERROR_EMPTY_TEXT = "EMPTY_TEXT"
READINESS_ERROR_EMPTY_SENTENCE_ITEMS = "EMPTY_SENTENCE_ITEMS"
READINESS_ERROR_EMPTY_VISUAL_BEATS = "EMPTY_VISUAL_BEATS"
READINESS_ERROR_MISSING_AUDIO = "MISSING_AUDIO"
READINESS_ERROR_MISSING_ALIGNMENT = "MISSING_ALIGNMENT"
READINESS_ERROR_AUDIO_FAILED = "AUDIO_FAILED"
READINESS_ERROR_AUDIO_STALE = "AUDIO_STALE"
READINESS_ERROR_AUDIO_DURATION_MISSING = "AUDIO_DURATION_MISSING"
READINESS_ERROR_NEEDS_USER_REVIEW = "NEEDS_USER_REVIEW"
READINESS_ERROR_PLAN_STALE = "PLAN_STALE"

READINESS_SEVERITY_WARNING = "WARNING"
READINESS_SEVERITY_BLOCKER = "BLOCKER"

# --- Cut Plan (Phase 8): confirmed_voiceover_project_plan.json -> technischer
# Schnittplan-Entwurf. Eigener Namensraum, KEINE Wiederverwendung von
# edit_plan_rules.json/EDIT_PLAN_* — schützt die bestehende Pipeline (§3). ---
CUT_PLAN_SUBDIR = "cut_plan"
CUT_PLAN_SETTINGS_FILENAME = "cut_plan_settings.json"
CUT_PLAN_DRAFT_FILENAME = "cut_plan.draft.json"
CUT_PLAN_VALIDATION_REPORT_FILENAME = "cut_plan.validation_report.json"
CUT_PLAN_CONFIRMED_FILENAME = "cut_plan.confirmed.json"
CUT_PLAN_TRACE_FILENAME = "cut_plan.trace.json"
CUT_PLAN_SUPPLEMENT_REQUESTS_FILENAME = "supplement_requests.from_cut_plan.json"
# Phase 8.6: isolierte Supplement Bridge — ausschließlich unter
# _otio/voiceover_generation/cut_plan/, NIEMALS unter _otio/supplement/.
CUT_PLAN_SUPPLEMENT_CANDIDATES_FILENAME = "supplement_candidates.json"
CUT_PLAN_SUPPLEMENT_ASSETS_SUBDIR = "supplement_assets"
CUT_PLAN_SUPPLEMENT_RUNS_SUBDIR = "supplement_runs"
CUT_PLAN_SUPPLEMENT_MANIFEST_FILENAME = "supplement_manifest.json"

# Phase 9.1: isolierte EditPlan-Bridge — ausschließlich unter
# _otio/voiceover_generation/cut_plan/edit_plan_bridge/, NIEMALS unter
# _otio/edit_plan/ oder _otio/exports/.
CUT_PLAN_EDIT_PLAN_BRIDGE_SUBDIR = "edit_plan_bridge"
CUT_PLAN_EDIT_PLAN_BRIDGE_DRAFT_FILENAME = "edit_plan_from_cut_plan.draft.json"
CUT_PLAN_EDIT_PLAN_BRIDGE_TRACE_FILENAME = "edit_plan_bridge_trace.json"
CUT_PLAN_EDIT_PLAN_BRIDGE_VALIDATION_REPORT_FILENAME = "edit_plan_bridge_validation_report.json"
CUT_PLAN_EDIT_PLAN_BRIDGE_AUDIO_PLAN_FILENAME = "bridge_audio_plan.json"
# Phase 9.3: Confirm/Freeze der EditPlan Bridge — weiterhin isolierter
# Snapshot, KEIN Produktions-EditPlan, KEIN locked Plan, KEIN OTIO-Export.
CUT_PLAN_EDIT_PLAN_BRIDGE_CONFIRMED_DRAFT_FILENAME = "edit_plan_from_cut_plan.confirmed.json"
CUT_PLAN_EDIT_PLAN_BRIDGE_CONFIRMED_AUDIO_PLAN_FILENAME = "bridge_audio_plan.confirmed.json"
CUT_PLAN_EDIT_PLAN_BRIDGE_CONFIRMED_TRACE_FILENAME = "edit_plan_bridge_trace.confirmed.json"
CUT_PLAN_EDIT_PLAN_BRIDGE_CONFIRM_MANIFEST_FILENAME = "edit_plan_bridge_confirm_manifest.json"

EDIT_PLAN_BRIDGE_CONFIRM_STATUS_CONFIRMED = "CONFIRMED"

EDIT_PLAN_BRIDGE_VALIDATION_STATUS_PASS = "PASS"
EDIT_PLAN_BRIDGE_VALIDATION_STATUS_WARNING = "WARNING"
EDIT_PLAN_BRIDGE_VALIDATION_STATUS_BLOCKED = "BLOCKED"

# TimelineItem.type für aus CutPlanAudioItem gebaute Bridge-Items — bewusst
# KEIN bestehender Produktions-Typ (siehe timeline_plan_builder.VISUAL_VIDEO_TYPES/
# NARRATION_VISUAL_TYPES), damit ein versehentlich in die Produktionspipeline
# geratener Bridge-Draft dort nicht fälschlich als Video-/Bild-Visual erkannt wird.
EDIT_PLAN_BRIDGE_TIMELINE_ITEM_TYPE_VOICEOVER_AUDIO = "voiceover_audio"
# EditPlanDocument.candidate_status-Marker für Bridge-Drafts (§11: „deutlich
# als bridge draft markieren“) — kollidiert nicht mit Produktions-Werten wie
# "BLOCKED".
EDIT_PLAN_BRIDGE_CANDIDATE_STATUS_MARKER = "EDIT_PLAN_BRIDGE_DRAFT"

# EditPlanBridgeValidationError.type
EDIT_PLAN_BRIDGE_ERROR_CONFIRMED_CUT_PLAN_MISSING = "CONFIRMED_CUT_PLAN_MISSING"
EDIT_PLAN_BRIDGE_ERROR_CONFIRMED_CUT_PLAN_STALE = "CONFIRMED_CUT_PLAN_STALE"
EDIT_PLAN_BRIDGE_ERROR_CONFIRMED_CUT_PLAN_NOT_CONFIRMED = "CONFIRMED_CUT_PLAN_NOT_CONFIRMED"
EDIT_PLAN_BRIDGE_ERROR_CONFIRMED_CUT_PLAN_HAS_BLOCKERS = "CONFIRMED_CUT_PLAN_HAS_BLOCKERS"
EDIT_PLAN_BRIDGE_ERROR_AUDIO_ITEM_MISSING = "AUDIO_ITEM_MISSING"
EDIT_PLAN_BRIDGE_ERROR_VISUAL_ITEM_MISSING = "VISUAL_ITEM_MISSING"
EDIT_PLAN_BRIDGE_ERROR_ZERO_OR_NEGATIVE_DURATION = "ZERO_OR_NEGATIVE_DURATION"
EDIT_PLAN_BRIDGE_ERROR_AUDIO_SOURCE_NOT_ZERO = "AUDIO_SOURCE_NOT_ZERO"
EDIT_PLAN_BRIDGE_ERROR_AUDIO_FILE_MISSING = "AUDIO_FILE_MISSING"
EDIT_PLAN_BRIDGE_ERROR_ASSET_FILE_MISSING = "ASSET_FILE_MISSING"
EDIT_PLAN_BRIDGE_ERROR_TIMELINE_OVERLAP = "TIMELINE_OVERLAP"
EDIT_PLAN_BRIDGE_ERROR_BLACK_GAP_DURING_AUDIO = "BLACK_GAP_DURING_AUDIO"
EDIT_PLAN_BRIDGE_ERROR_NON_MONOTONIC_TIMELINE = "NON_MONOTONIC_TIMELINE"
EDIT_PLAN_BRIDGE_ERROR_SECRET_LEAK_DETECTED = "SECRET_LEAK_DETECTED"
# Phase 9.2: Bridge-Hardening — Boundary-Chaining + Audio-Kompatibilität.
EDIT_PLAN_BRIDGE_ERROR_VISUAL_TIMELINE_GAP = "VISUAL_TIMELINE_GAP"
EDIT_PLAN_BRIDGE_ERROR_SOURCE_RANGE_INVALID = "SOURCE_RANGE_INVALID"
EDIT_PLAN_BRIDGE_ERROR_VIDEO_SOURCE_EXCEEDS_DURATION = "VIDEO_SOURCE_EXCEEDS_DURATION"
EDIT_PLAN_BRIDGE_ERROR_AUDIO_PLAN_MISSING = "AUDIO_PLAN_MISSING"
EDIT_PLAN_BRIDGE_ERROR_AUDIO_PLAN_MISMATCH = "AUDIO_PLAN_MISMATCH"

# --- Phase 10.1: Production EditPlan Staging — isoliertes Staging-Paket aus
# dem bestätigten EditPlan-Bridge-Snapshot, ausschließlich unter
# _otio/voiceover_generation/cut_plan/production_edit_plan_staging/. NIEMALS
# unter _otio/edit_plan/ (das erfolgt erst in einer späteren, separaten
# Promote-Phase). ---
PRODUCTION_EDIT_PLAN_STAGING_SUBDIR = "production_edit_plan_staging"
PRODUCTION_EDIT_PLAN_PACKAGE_FILENAME = "production_edit_plan_package.json"
PRODUCTION_EDIT_PLAN_STAGED_EDIT_PLANS_SUBDIR = "staged_edit_plans"
PRODUCTION_EDIT_PLAN_STAGED_EDIT_PLAN_FILENAME = "edit_plan.json"
PRODUCTION_EDIT_PLAN_MAPPING_TRACE_FILENAME = "production_edit_plan_mapping_trace.json"
PRODUCTION_EDIT_PLAN_VALIDATION_REPORT_FILENAME = "production_edit_plan_validation_report.json"

# ProductionEditPlanPackage.status / ProductionEditPlanValidationReport.status
PRODUCTION_EDIT_PLAN_STATUS_STAGED = "STAGED"
PRODUCTION_EDIT_PLAN_STATUS_NEEDS_REVIEW = "NEEDS_REVIEW"
PRODUCTION_EDIT_PLAN_STATUS_BLOCKED = "BLOCKED"

# EditPlanDocument.candidate_status-Marker für gestagte Produktions-Pläne —
# deutlich von EDIT_PLAN_BRIDGE_CANDIDATE_STATUS_MARKER unterschieden, damit
# man am Wert allein erkennt, aus welcher Phase ein Draft stammt.
PRODUCTION_EDIT_PLAN_CANDIDATE_STATUS_STAGING_DRAFT = "PRODUCTION_EDIT_PLAN_STAGING_DRAFT"

# ProductionEditPlanValidationError.type — Grundset für Phase 10.1.
PRODUCTION_EDIT_PLAN_ERROR_BRIDGE_SNAPSHOT_MISSING = "BRIDGE_SNAPSHOT_MISSING"
PRODUCTION_EDIT_PLAN_ERROR_BRIDGE_SNAPSHOT_STALE = "BRIDGE_SNAPSHOT_STALE"
PRODUCTION_EDIT_PLAN_ERROR_VOICEOVER_AUDIO_ITEM_LEAKED = "VOICEOVER_AUDIO_ITEM_LEAKED"
PRODUCTION_EDIT_PLAN_ERROR_MISSING_VOICEOVER_PLAN = "MISSING_VOICEOVER_PLAN"
PRODUCTION_EDIT_PLAN_ERROR_LOCAL_TIMELINE_MAPPING_ERROR = "LOCAL_TIMELINE_MAPPING_ERROR"
PRODUCTION_EDIT_PLAN_ERROR_PRODUCTION_TIMELINE_VALIDATION_FAILED = "PRODUCTION_TIMELINE_VALIDATION_FAILED"
# Phase 10.2: Section-Reconciliation + Mapping-Sanity-Checks (Grundset,
# volle Timeline-/Voiceover-Validierung folgt erst in Phase 10.3).
PRODUCTION_EDIT_PLAN_ERROR_VISUAL_WITHOUT_AUDIO_SECTION = "VISUAL_WITHOUT_AUDIO_SECTION"
PRODUCTION_EDIT_PLAN_ERROR_NO_VISUAL_ITEMS_FOR_SECTION = "NO_VISUAL_ITEMS_FOR_SECTION"
PRODUCTION_EDIT_PLAN_ERROR_SHOT_SYNTHESIS_FAILED = "SHOT_SYNTHESIS_FAILED"
PRODUCTION_EDIT_PLAN_ERROR_ZERO_OR_NEGATIVE_DURATION = "ZERO_OR_NEGATIVE_DURATION"

# ProductionEditPlanValidationReport.status — Phase 10.3 volle Revalidierung.
PRODUCTION_EDIT_PLAN_VALIDATION_STATUS_PASS = "PASS"
PRODUCTION_EDIT_PLAN_VALIDATION_STATUS_WARNING = "WARNING"
PRODUCTION_EDIT_PLAN_VALIDATION_STATUS_BLOCKED = "BLOCKED"

# Phase 10.3: ProductionEditPlanValidationError.type — vollständige
# Revalidierung des Staging-Pakets (Package/Trace-Ebene). Wo bereits ein
# passender Phase-10.1/10.2-Fehlertyp existiert (z. B. MISSING_VOICEOVER_PLAN,
# VOICEOVER_AUDIO_ITEM_LEAKED, PRODUCTION_TIMELINE_VALIDATION_FAILED), wird
# dieser wiederverwendet statt dupliziert.
PRODUCTION_EDIT_PLAN_ERROR_PRODUCTION_STAGING_MISSING = "PRODUCTION_STAGING_MISSING"
PRODUCTION_EDIT_PLAN_ERROR_PRODUCTION_STAGING_STALE = "PRODUCTION_STAGING_STALE"
PRODUCTION_EDIT_PLAN_ERROR_PRODUCTION_STAGING_TRACE_MISSING = "PRODUCTION_STAGING_TRACE_MISSING"
PRODUCTION_EDIT_PLAN_ERROR_STAGED_EDIT_PLAN_MISSING = "STAGED_EDIT_PLAN_MISSING"
PRODUCTION_EDIT_PLAN_ERROR_STAGED_EDIT_PLAN_HASH_MISMATCH = "STAGED_EDIT_PLAN_HASH_MISMATCH"
PRODUCTION_EDIT_PLAN_ERROR_STAGED_EDIT_PLAN_CONFIRMED_TRUE = "STAGED_EDIT_PLAN_CONFIRMED_TRUE"
PRODUCTION_EDIT_PLAN_ERROR_STAGED_EDIT_PLAN_STATUS_INVALID = "STAGED_EDIT_PLAN_STATUS_INVALID"
PRODUCTION_EDIT_PLAN_ERROR_STAGED_EDIT_PLAN_EMPTY_TIMELINE = "STAGED_EDIT_PLAN_EMPTY_TIMELINE"
PRODUCTION_EDIT_PLAN_ERROR_STAGED_EDIT_PLAN_EMPTY_SHOTS = "STAGED_EDIT_PLAN_EMPTY_SHOTS"
PRODUCTION_EDIT_PLAN_ERROR_VOICEOVER_PLAN_MISSING = "VOICEOVER_PLAN_MISSING"
PRODUCTION_EDIT_PLAN_ERROR_VOICEOVER_AUDIO_PATH_MISSING = "VOICEOVER_AUDIO_PATH_MISSING"
PRODUCTION_EDIT_PLAN_ERROR_VOICEOVER_DURATION_INVALID = "VOICEOVER_DURATION_INVALID"
PRODUCTION_EDIT_PLAN_ERROR_VOICEOVER_TIMING_INVALID = "VOICEOVER_TIMING_INVALID"
PRODUCTION_EDIT_PLAN_ERROR_VOICEOVER_DURATION_SOURCE_INVALID = "VOICEOVER_DURATION_SOURCE_INVALID"
PRODUCTION_EDIT_PLAN_ERROR_VOICEOVER_TRIM_POLICY_INVALID = "VOICEOVER_TRIM_POLICY_INVALID"
PRODUCTION_EDIT_PLAN_ERROR_TIMELINE_ITEM_DURATION_INVALID = "TIMELINE_ITEM_DURATION_INVALID"
PRODUCTION_EDIT_PLAN_ERROR_TIMELINE_ITEM_SOURCE_RANGE_INVALID = "TIMELINE_ITEM_SOURCE_RANGE_INVALID"
PRODUCTION_EDIT_PLAN_ERROR_TIMELINE_ITEM_ASSET_MISSING = "TIMELINE_ITEM_ASSET_MISSING"
PRODUCTION_EDIT_PLAN_ERROR_TIMELINE_ITEM_TYPE_INVALID = "TIMELINE_ITEM_TYPE_INVALID"
PRODUCTION_EDIT_PLAN_ERROR_SHOT_COUNT_MISMATCH = "SHOT_COUNT_MISMATCH"
PRODUCTION_EDIT_PLAN_ERROR_SHOT_DURATION_INVALID = "SHOT_DURATION_INVALID"
PRODUCTION_EDIT_PLAN_ERROR_SHOT_TIMING_OUTSIDE_VOICEOVER = "SHOT_TIMING_OUTSIDE_VOICEOVER"
PRODUCTION_EDIT_PLAN_ERROR_MAPPING_TRACE_MISSING = "MAPPING_TRACE_MISSING"
PRODUCTION_EDIT_PLAN_ERROR_MAPPING_TRACE_ITEM_MISSING = "MAPPING_TRACE_ITEM_MISSING"
PRODUCTION_EDIT_PLAN_ERROR_MAPPING_TRACE_ROUNDTRIP_FAILED = "MAPPING_TRACE_ROUNDTRIP_FAILED"
PRODUCTION_EDIT_PLAN_ERROR_SECRET_LEAK_DETECTED = "SECRET_LEAK_DETECTED"
# Wiederverwendete Phase-10.1/10.2-Typen (Aliase für Phase-10.3-Aufrufer, damit
# der 10.3-Fehlerkatalog vollständig unter den PRODUCTION_EDIT_PLAN_ERROR_*-
# Namen auffindbar ist, ohne bestehende Konstanten zu duplizieren):
# - VOICEOVER_AUDIO_ITEM_LEAKED -> PRODUCTION_EDIT_PLAN_ERROR_VOICEOVER_AUDIO_ITEM_LEAKED
# - TIMELINE_VALIDATION_FAILED -> PRODUCTION_EDIT_PLAN_ERROR_PRODUCTION_TIMELINE_VALIDATION_FAILED

# --- Phase 10.5: Production EditPlan Promote Readiness / Dry Run — prüft rein
# lesend, was ein SPÄTERER Promote nach `_otio/edit_plan/` tun würde. Schreibt
# ausschließlich unter production_edit_plan_staging/, NIEMALS nach
# `_otio/edit_plan/`, kein tatsächliches Kopieren, kein Lock, kein OTIO. ---
PRODUCTION_EDIT_PLAN_PROMOTE_READINESS_FILENAME = "production_edit_plan_promote_readiness.json"
PRODUCTION_EDIT_PLAN_PROMOTE_DRY_RUN_TRACE_FILENAME = "production_edit_plan_promote_dry_run_trace.json"

# ProductionEditPlanPromoteReadinessDocument.status
PRODUCTION_EDIT_PLAN_PROMOTE_READINESS_STATUS_READY = "READY"
PRODUCTION_EDIT_PLAN_PROMOTE_READINESS_STATUS_NEEDS_REVIEW = "NEEDS_REVIEW"
PRODUCTION_EDIT_PLAN_PROMOTE_READINESS_STATUS_BLOCKED = "BLOCKED"

# ProductionEditPlanPromoteSectionReadiness.promote_action /
# ProductionEditPlanPromoteDryRunTraceEntry.promote_action
PRODUCTION_EDIT_PLAN_PROMOTE_ACTION_WOULD_CREATE = "WOULD_CREATE"
PRODUCTION_EDIT_PLAN_PROMOTE_ACTION_WOULD_OVERWRITE = "WOULD_OVERWRITE"
PRODUCTION_EDIT_PLAN_PROMOTE_ACTION_WOULD_SKIP_INTRO = "WOULD_SKIP_INTRO"
PRODUCTION_EDIT_PLAN_PROMOTE_ACTION_BLOCKED = "BLOCKED"

# Zusätzliche Fehlertypen, die es in Phase 10.3 noch nicht gab (Rest wird
# additiv aus dem Phase-10.3-Katalog wiederverwendet, siehe Docstring von
# production_edit_plan_promote_readiness.py):
PRODUCTION_EDIT_PLAN_ERROR_VALIDATION_REPORT_MISSING = "VALIDATION_REPORT_MISSING"
PRODUCTION_EDIT_PLAN_ERROR_VALIDATION_REPORT_NOT_PASS = "VALIDATION_REPORT_NOT_PASS"
PRODUCTION_EDIT_PLAN_ERROR_VALIDATION_REPORT_STALE = "VALIDATION_REPORT_STALE"
PRODUCTION_EDIT_PLAN_ERROR_SECTION_HAS_BLOCKERS = "SECTION_HAS_BLOCKERS"
PRODUCTION_EDIT_PLAN_ERROR_EXISTING_PRODUCTION_PLAN_UNREADABLE = "EXISTING_PRODUCTION_PLAN_UNREADABLE"

# Cut Plan Settings — Defaults (verbindliche Werte laut Nutzerentscheidung §1/§3/§5)
CUT_PLAN_DEFAULT_INITIAL_AUDIO_OFFSET_SEC = 1.0
CUT_PLAN_DEFAULT_PAUSE_BETWEEN_SECTIONS_SEC = 0.25
CUT_PLAN_DEFAULT_SECTION_VISUAL_PREROLL_SEC = 0.0
CUT_PLAN_DEFAULT_VIDEO_HEAD_TRIM_SEC = 1.0  # gilt nur für Video, nie für Bild/Audio
CUT_PLAN_DEFAULT_SHOT_MIN_SEC = 3.0
CUT_PLAN_DEFAULT_SHOT_MAX_SEC = 8.0
CUT_PLAN_DEFAULT_MAX_ASSET_USAGE = 2
CUT_PLAN_DEFAULT_MIN_ASSET_REUSE_DISTANCE_SHOTS = 0
CUT_PLAN_DEFAULT_TIMELINE_FPS = 25
CUT_PLAN_DEFAULT_TIMELINE_WIDTH = 3840
CUT_PLAN_DEFAULT_TIMELINE_HEIGHT = 2160

# CutPlanDocument.status
CUT_PLAN_STATUS_DRAFT = "DRAFT"
CUT_PLAN_STATUS_VALIDATED = "VALIDATED"
CUT_PLAN_STATUS_NEEDS_REVIEW = "NEEDS_REVIEW"
CUT_PLAN_STATUS_CONFIRMED = "CONFIRMED"
CUT_PLAN_STATUS_BLOCKED = "BLOCKED"
CUT_PLAN_STATUS_CHOICES = (
    CUT_PLAN_STATUS_DRAFT,
    CUT_PLAN_STATUS_VALIDATED,
    CUT_PLAN_STATUS_NEEDS_REVIEW,
    CUT_PLAN_STATUS_CONFIRMED,
    CUT_PLAN_STATUS_BLOCKED,
)

# CutPlanItem.asset_selection_status
CUT_PLAN_ASSET_SELECTION_UNRESOLVED = "UNRESOLVED"
CUT_PLAN_ASSET_SELECTION_PRIMARY_USED = "PRIMARY_USED"
CUT_PLAN_ASSET_SELECTION_BACKUP_USED = "BACKUP_USED"
CUT_PLAN_ASSET_SELECTION_SUPPLEMENT_REQUIRED = "SUPPLEMENT_REQUIRED"
CUT_PLAN_ASSET_SELECTION_SUPPLEMENT_USED = "SUPPLEMENT_USED"
CUT_PLAN_ASSET_SELECTION_BLOCKED = "BLOCKED"
CUT_PLAN_ASSET_SELECTION_CHOICES = (
    CUT_PLAN_ASSET_SELECTION_UNRESOLVED,
    CUT_PLAN_ASSET_SELECTION_PRIMARY_USED,
    CUT_PLAN_ASSET_SELECTION_BACKUP_USED,
    CUT_PLAN_ASSET_SELECTION_SUPPLEMENT_REQUIRED,
    CUT_PLAN_ASSET_SELECTION_SUPPLEMENT_USED,
    CUT_PLAN_ASSET_SELECTION_BLOCKED,
)

# Phase 8.6: CutPlanSupplementRequest.status
CUT_PLAN_SUPPLEMENT_REQUEST_STATUS_OPEN = "OPEN"
CUT_PLAN_SUPPLEMENT_REQUEST_STATUS_CANDIDATES_FOUND = "CANDIDATES_FOUND"
CUT_PLAN_SUPPLEMENT_REQUEST_STATUS_ACCEPTED = "ACCEPTED"
CUT_PLAN_SUPPLEMENT_REQUEST_STATUS_REJECTED = "REJECTED"
CUT_PLAN_SUPPLEMENT_REQUEST_STATUS_FAILED = "FAILED"
CUT_PLAN_SUPPLEMENT_REQUEST_STATUS_CHOICES = (
    CUT_PLAN_SUPPLEMENT_REQUEST_STATUS_OPEN,
    CUT_PLAN_SUPPLEMENT_REQUEST_STATUS_CANDIDATES_FOUND,
    CUT_PLAN_SUPPLEMENT_REQUEST_STATUS_ACCEPTED,
    CUT_PLAN_SUPPLEMENT_REQUEST_STATUS_REJECTED,
    CUT_PLAN_SUPPLEMENT_REQUEST_STATUS_FAILED,
)

# Phase 8.6: CutPlanSupplementCandidatesDocument.status
CUT_PLAN_SUPPLEMENT_CANDIDATES_STATUS_READY = "READY"
CUT_PLAN_SUPPLEMENT_CANDIDATES_STATUS_NO_RESULTS = "NO_RESULTS"
CUT_PLAN_SUPPLEMENT_CANDIDATES_STATUS_FAILED = "FAILED"

# Phase 8.6: CutPlanSupplementAsset.status
CUT_PLAN_SUPPLEMENT_ASSET_STATUS_ACQUIRED = "ACQUIRED"
CUT_PLAN_SUPPLEMENT_ASSET_STATUS_FAILED = "FAILED"

# CutPlanItem.duration_strategy
CUT_PLAN_DURATION_STRATEGY_SINGLE_SHOT = "SINGLE_SHOT"
CUT_PLAN_DURATION_STRATEGY_SPLIT = "SPLIT"
CUT_PLAN_DURATION_STRATEGY_MERGED = "MERGED"
CUT_PLAN_DURATION_STRATEGY_CHOICES = (
    CUT_PLAN_DURATION_STRATEGY_SINGLE_SHOT,
    CUT_PLAN_DURATION_STRATEGY_SPLIT,
    CUT_PLAN_DURATION_STRATEGY_MERGED,
)

# CutPlanValidationReport.status
CUT_PLAN_VALIDATION_STATUS_PASS = "PASS"
CUT_PLAN_VALIDATION_STATUS_WARNING = "WARNING"
CUT_PLAN_VALIDATION_STATUS_BLOCKED = "BLOCKED"

# CutPlanValidationError.must_be_fixed_by
CUT_PLAN_FIX_BY_PYTHON = "python"
CUT_PLAN_FIX_BY_LLM = "llm"
CUT_PLAN_FIX_BY_USER = "user"

# CutPlanValidationError.type — Fehlertypen vorbereitet für Phase 8.4
# (Validierung selbst ist in Phase 8.1 noch NICHT implementiert).
CUT_PLAN_ERROR_SOURCE_PLAN_NOT_READY = "SOURCE_PLAN_NOT_READY"
CUT_PLAN_ERROR_MISSING_AUDIO = "MISSING_AUDIO"
CUT_PLAN_ERROR_MISSING_ALIGNMENT = "MISSING_ALIGNMENT"
CUT_PLAN_ERROR_INVALID_AUDIO_PATH = "INVALID_AUDIO_PATH"
CUT_PLAN_ERROR_INVALID_ASSET_ID = "INVALID_ASSET_ID"
CUT_PLAN_ERROR_MISSING_ASSET_MAPPING = "MISSING_ASSET_MAPPING"
CUT_PLAN_ERROR_ASSET_FILE_MISSING = "ASSET_FILE_MISSING"
CUT_PLAN_ERROR_ASSET_TOO_SHORT = "ASSET_TOO_SHORT"
CUT_PLAN_ERROR_SOURCE_RANGE_INVALID = "SOURCE_RANGE_INVALID"
CUT_PLAN_ERROR_SHOT_TOO_SHORT = "SHOT_TOO_SHORT"
CUT_PLAN_ERROR_SHOT_TOO_LONG = "SHOT_TOO_LONG"
CUT_PLAN_ERROR_MAX_ASSET_USAGE_EXCEEDED = "MAX_ASSET_USAGE_EXCEEDED"
CUT_PLAN_ERROR_ASSET_REUSE_DISTANCE_TOO_SHORT = "ASSET_REUSE_DISTANCE_TOO_SHORT"
CUT_PLAN_ERROR_SUPPLEMENT_REQUIRED = "SUPPLEMENT_REQUIRED"
CUT_PLAN_ERROR_SUPPLEMENT_REASON_MISSING = "SUPPLEMENT_REASON_MISSING"
CUT_PLAN_ERROR_BLACK_GAP_DURING_VOICEOVER = "BLACK_GAP_DURING_VOICEOVER"
CUT_PLAN_ERROR_TIMELINE_OVERLAP = "TIMELINE_OVERLAP"
CUT_PLAN_ERROR_AUDIO_GAP_UNEXPECTED = "AUDIO_GAP_UNEXPECTED"
CUT_PLAN_ERROR_FRAME_ROUNDING_ERROR = "FRAME_ROUNDING_ERROR"
CUT_PLAN_ERROR_AMBIGUOUS_ASSET_ID = "AMBIGUOUS_ASSET_ID"
CUT_PLAN_ERROR_TYPES = (
    CUT_PLAN_ERROR_SOURCE_PLAN_NOT_READY,
    CUT_PLAN_ERROR_MISSING_AUDIO,
    CUT_PLAN_ERROR_MISSING_ALIGNMENT,
    CUT_PLAN_ERROR_INVALID_AUDIO_PATH,
    CUT_PLAN_ERROR_INVALID_ASSET_ID,
    CUT_PLAN_ERROR_MISSING_ASSET_MAPPING,
    CUT_PLAN_ERROR_ASSET_FILE_MISSING,
    CUT_PLAN_ERROR_ASSET_TOO_SHORT,
    CUT_PLAN_ERROR_SOURCE_RANGE_INVALID,
    CUT_PLAN_ERROR_SHOT_TOO_SHORT,
    CUT_PLAN_ERROR_SHOT_TOO_LONG,
    CUT_PLAN_ERROR_MAX_ASSET_USAGE_EXCEEDED,
    CUT_PLAN_ERROR_ASSET_REUSE_DISTANCE_TOO_SHORT,
    CUT_PLAN_ERROR_SUPPLEMENT_REQUIRED,
    CUT_PLAN_ERROR_SUPPLEMENT_REASON_MISSING,
    CUT_PLAN_ERROR_BLACK_GAP_DURING_VOICEOVER,
    CUT_PLAN_ERROR_TIMELINE_OVERLAP,
    CUT_PLAN_ERROR_AUDIO_GAP_UNEXPECTED,
    CUT_PLAN_ERROR_FRAME_ROUNDING_ERROR,
    CUT_PLAN_ERROR_AMBIGUOUS_ASSET_ID,
)

MODEL_COMPARISON_SUBDIR = "model_comparison_runs"
MODEL_COMPARISON_SUMMARY_FILENAME = "model_comparison_summary.json"
MODEL_COMPARISON_PRESETS: dict[str, tuple[str, ...]] = {
    "gemini": ("gemini-3.1-pro-preview", "gemini-3.1-flash-lite"),
    "anthropic": ("anthropic:claude-sonnet-5", "anthropic:claude-opus-4-8"),
    "openai": ("openai:gpt-5.5", "openai:gpt-5.4-mini"),
}
EXPORTS_SUBDIR = "exports"
CLEAN_MEDIA_OUTPUT_SUBDIR = "clean"
CLEAN_MEDIA_MANIFEST_SUBDIR = "clean_media"
DEFAULT_SHOT_MIN_SEC = 3.0
DEFAULT_SHOT_MAX_SEC = 8.0
DEFAULT_AUDIO_OFFSET_SEC = 1.0
DEFAULT_SECTION_OUTRO_SEC = 5.0
MAX_GEMINI_PLAN_ATTEMPTS = 3
OUTRO_BEAT_ID = "outro_001"
DEFAULT_TEXT_SPLITTERS = (", und ", ", ", " und ")
FALLBACK_SOURCE_LOCAL = "local"
FALLBACK_SOURCE_MISSING = "missing"
FALLBACK_SOURCE_ADOBE_STOCK = "adobe_stock"
FALLBACK_SOURCE_PEXELS = "pexels"
FALLBACK_SOURCE_GEMINI_IMAGE = "gemini_image"
FALLBACK_SOURCE_CHOICES = (
    FALLBACK_SOURCE_LOCAL,
    FALLBACK_SOURCE_ADOBE_STOCK,
    FALLBACK_SOURCE_PEXELS,
    FALLBACK_SOURCE_GEMINI_IMAGE,
)
FALLBACK_SOURCE_LABELS = {
    FALLBACK_SOURCE_LOCAL: "Lokale Assets",
    FALLBACK_SOURCE_ADOBE_STOCK: "Adobe Stock",
    FALLBACK_SOURCE_PEXELS: "Pexels & Co.",
    FALLBACK_SOURCE_GEMINI_IMAGE: "KI-Bild (Gemini)",
}
DEFAULT_FALLBACK_ORDER = (
    FALLBACK_SOURCE_LOCAL,
    FALLBACK_SOURCE_ADOBE_STOCK,
    FALLBACK_SOURCE_PEXELS,
    FALLBACK_SOURCE_GEMINI_IMAGE,
)

SUPPLEMENT_SUBDIR = "supplement"
SUPPLEMENT_REQUESTS_FILENAME = "supplement_requests.json"
SUPPLEMENT_MANIFEST_FILENAME = "supplement_manifest.json"
SUPPLEMENT_ERRORS_FILENAME = "supplement_errors.json"
PEXELS_DEBUG_REPORT_FILENAME = "pexels_debug_report.json"
INVENTORY_DELTA_SUFFIX = ".inventory_delta.json"
SUPPLEMENTAL_FOLDER_NAME = "_supplemental"
DEFAULT_COVERAGE_THRESHOLD = 0.55

MATCH_QUALITY_SEHR_GUT = "sehr_gut"
MATCH_QUALITY_GUT = "gut"
MATCH_QUALITY_MITTEL = "mittel"
MATCH_QUALITY_UNPASSEND = "unpassend"

MATCH_QUALITY_CHOICES = (
    MATCH_QUALITY_SEHR_GUT,
    MATCH_QUALITY_GUT,
    MATCH_QUALITY_MITTEL,
    MATCH_QUALITY_UNPASSEND,
)

MATCH_QUALITY_LABELS = {
    MATCH_QUALITY_SEHR_GUT: "Sehr gut",
    MATCH_QUALITY_GUT: "Gut",
    MATCH_QUALITY_MITTEL: "Mittel",
    MATCH_QUALITY_UNPASSEND: "Unpassend",
}

PROVIDER_STATUS_MOCK = "MOCK"
PROVIDER_STATUS_CONFIG_MISSING = "CONFIG_MISSING"
PROVIDER_STATUS_READY = "READY"
PROVIDER_STATUS_ERROR = "ERROR"

CANDIDATE_STATUS_FOUND = "CANDIDATE_FOUND"
CANDIDATE_STATUS_MOCK_ONLY = "CANDIDATE_MOCK_ONLY"
CANDIDATE_STATUS_SELECTED = "SELECTED"
CANDIDATE_STATUS_ACQUIRE_STARTED = "ACQUIRE_STARTED"
CANDIDATE_STATUS_ACQUIRED = "ACQUIRED"
CANDIDATE_STATUS_DOWNLOAD_FAILED = "DOWNLOAD_FAILED"
CANDIDATE_STATUS_REJECTED_ASPECT_RATIO = "REJECTED_ASPECT_RATIO"
CANDIDATE_STATUS_NOT_DOWNLOADABLE_16_9 = "NOT_DOWNLOADABLE_16_9"
CANDIDATE_STATUS_GENERATION_FAILED = "GENERATION_FAILED"
CANDIDATE_STATUS_IMPORTED_MANUALLY = "IMPORTED_MANUALLY"
CANDIDATE_STATUS_ANALYSIS_PENDING = "ANALYSIS_PENDING"
CANDIDATE_STATUS_ANALYSIS_COMPLETE = "ANALYSIS_COMPLETE"
CANDIDATE_STATUS_INVENTORY_ADDED = "INVENTORY_ADDED"

REQUEST_STATUS_PENDING_SOURCE = "PENDING_SOURCE_SELECTION"
REQUEST_STATUS_SOURCE_SELECTED = "SOURCE_SELECTED"
REQUEST_STATUS_CANDIDATES_FOUND = "CANDIDATES_FOUND"
REQUEST_STATUS_AWAITING_SELECTION = "AWAITING_USER_SELECTION"
REQUEST_STATUS_ACQUIRE_FAILED = "ACQUIRE_FAILED"
REQUEST_STATUS_ASSET_ACQUIRED = "ASSET_ACQUIRED"
REQUEST_STATUS_ANALYSIS_PENDING = "ANALYSIS_PENDING"
REQUEST_STATUS_INVENTORY_UPDATED = "INVENTORY_UPDATED"
REQUEST_STATUS_READY_FOR_REPLAN = "READY_FOR_REPLAN"

SUPPLEMENT_SOURCE_ADOBE = "adobe_stock"
SUPPLEMENT_SOURCE_PEXELS = "pexels"
SUPPLEMENT_SOURCE_GOOGLE = "google_search"
SUPPLEMENT_SOURCE_NANO_BANANA = "nano_banana"
SUPPLEMENT_SOURCE_MANUAL = "manual"

SUPPLEMENT_SOURCE_LABELS = {
    SUPPLEMENT_SOURCE_ADOBE: "Adobe Stock",
    SUPPLEMENT_SOURCE_PEXELS: "Pexels",
    SUPPLEMENT_SOURCE_GOOGLE: "Google Suche",
    SUPPLEMENT_SOURCE_NANO_BANANA: "Nano Banana / KI-Bild",
    SUPPLEMENT_SOURCE_MANUAL: "Manuell später",
}

ASSET_ORIGIN_LOCAL = "local_original"
ASSET_ORIGIN_ADOBE = "adobe_stock"
ASSET_ORIGIN_PEXELS = "pexels"
ASSET_ORIGIN_GOOGLE = "google_search"
ASSET_ORIGIN_NANO_BANANA = "nano_banana"
ASSET_ORIGIN_MANUAL = "manual"

RIGHTS_STATUS_APPROVED = "APPROVED"
RIGHTS_STATUS_NEEDS_LICENSE_REVIEW = "NEEDS_LICENSE_REVIEW"
RIGHTS_STATUS_GENERATED_APPROVED = "GENERATED_APPROVED"
RIGHTS_STATUS_NEEDS_REVIEW = "NEEDS_REVIEW"


def resolve_voice_backend(backend: str | None) -> str:
    if backend and backend.strip() in VOICE_BACKEND_CHOICES:
        return backend.strip()
    return DEFAULT_VOICE_BACKEND


def resolve_whisper_model(model: str | None) -> str:
    if model and model.strip() in WHISPER_MODEL_CHOICES:
        return model.strip()
    return DEFAULT_WHISPER_MODEL
