"""Kartenplanung und -render für OTIO Enhanced.

Kapitel-ID ist der Original-``folder_name`` aus der bestätigten Dramaturgie.
Im Auto-Lauf: Plan erzeugen, Koordinaten prüfen/bestätigen, alle Karten rendern.
Manuelles Rendern bleibt zusätzlich über die Karten-Seite möglich.
"""

from otio_app.services.without_voiceover_enhanced.maps.models import (
    COORDINATE_STATUS_CONFIRMED,
    COORDINATE_STATUS_MANUAL,
    COORDINATE_STATUS_MISSING,
    COORDINATE_STATUS_NEEDS_REVIEW,
    COORDINATE_STATUS_RESOLVED,
    MAP_ANIMATION_OPENING,
    MAP_ANIMATION_TRANSITION,
    MAP_DURATION_FRAMES,
    MAP_FPS,
    MAP_HEADING_BY_LANGUAGE,
    MAP_MAX_PARALLEL_4K,
    MAP_MAX_PARALLEL_HD,
    MAP_RESOLUTION_4K,
    MAP_RESOLUTION_HD,
    RENDER_STATUS_LABELS,
    MapCoordinateRecord,
    MapCoordinatesDocument,
    MapPlanDocument,
    MapPlanItem,
    MapRenderSettings,
)
from otio_app.services.without_voiceover_enhanced.maps.geocode_service import (
    GeocodeError,
    GeocodeProgress,
    friendly_geocode_error,
    lookup_missing_coordinates,
    nominatim_geocode,
    NOMINATIM_USER_AGENT,
)
from otio_app.services.without_voiceover_enhanced.maps.map_render_job import (
    get_map_render_job_manager,
)
from otio_app.services.without_voiceover_enhanced.maps.remotion_payload import (
    remotion_payload,
)
from otio_app.services.without_voiceover_enhanced.maps.render_service import (
    MapRenderError,
    MapRenderer,
    packaged_renderer_root,
    selectable_maps,
)
from otio_app.services.without_voiceover_enhanced.maps.plan_service import (
    MapPlanError,
    apply_geocode_hits,
    build_map_plan,
    clamp_max_parallel,
    compute_plan_hash,
    confirm_all_valid_map_coordinates,
    confirm_map_place_coordinates,
    dramaturgy_fingerprint,
    load_map_coordinates,
    load_map_plan,
    load_map_settings,
    map_heading,
    map_language_prefix,
    map_output_filename,
    rebuild_saved_map_plan,
    save_map_coordinates,
    save_map_plan,
    save_map_settings,
    status_after_saving_coordinates,
    unique_chapter_places,
    update_coordinate_record,
)
from otio_app.services.without_voiceover_enhanced.maps.auto_run_maps import (
    maps_complete,
    run_maps_for_auto_run,
)

__all__ = [
    "COORDINATE_STATUS_CONFIRMED",
    "COORDINATE_STATUS_MANUAL",
    "COORDINATE_STATUS_MISSING",
    "COORDINATE_STATUS_NEEDS_REVIEW",
    "COORDINATE_STATUS_RESOLVED",
    "MAP_ANIMATION_OPENING",
    "MAP_ANIMATION_TRANSITION",
    "MAP_DURATION_FRAMES",
    "MAP_FPS",
    "MAP_HEADING_BY_LANGUAGE",
    "MAP_MAX_PARALLEL_4K",
    "MAP_MAX_PARALLEL_HD",
    "MAP_RESOLUTION_4K",
    "MAP_RESOLUTION_HD",
    "RENDER_STATUS_LABELS",
    "MapCoordinateRecord",
    "MapCoordinatesDocument",
    "MapPlanDocument",
    "GeocodeError",
    "GeocodeProgress",
    "NOMINATIM_USER_AGENT",
    "friendly_geocode_error",
    "MapPlanError",
    "MapPlanItem",
    "MapRenderSettings",
    "apply_geocode_hits",
    "build_map_plan",
    "clamp_max_parallel",
    "compute_plan_hash",
    "confirm_all_valid_map_coordinates",
    "confirm_map_place_coordinates",
    "dramaturgy_fingerprint",
    "load_map_coordinates",
    "load_map_plan",
    "load_map_settings",
    "lookup_missing_coordinates",
    "map_heading",
    "map_language_prefix",
    "map_output_filename",
    "maps_complete",
    "nominatim_geocode",
    "rebuild_saved_map_plan",
    "run_maps_for_auto_run",
    "save_map_coordinates",
    "save_map_plan",
    "save_map_settings",
    "status_after_saving_coordinates",
    "MapRenderError",
    "MapRenderer",
    "get_map_render_job_manager",
    "packaged_renderer_root",
    "remotion_payload",
    "selectable_maps",
    "unique_chapter_places",
    "update_coordinate_record",
]
